In [1]:
from vnstock import Listing

# Khởi tạo đối tượng Listing với nguồn VCI
listing = Listing(source='VCI')

In [5]:
# Lấy toàn bộ danh sách cổ phiếu
all_symbols = listing.all_symbols()

# Kiểm tra
print(f"Tổng số mã: {len(all_symbols)}")
print(all_symbols.head(10))

# Xuất Excel
all_symbols.to_excel(
    "all_symbols.xlsx",
    index=False
)

print("Đã xuất file all_symbols.xlsx")

Tổng số mã: 1753
  symbol                                         organ_name
0    YTC  Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...
1    YEG                     Công ty Cổ phần Tập đoàn Yeah1
2    YBM     Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái
3    YBC      Công ty Cổ phần Xi măng và Khoáng sản Yên Bái
4    XPH                    Công ty Cổ phần Xà phòng Hà Nội
5    XMP                Công ty Cổ phần Thủy điện Xuân Minh
6    XMD                  Công ty Cổ phần Xuân Mai - Đạo Tú
7    XMC        Công ty cổ phần Đầu tư và Xây dựng Xuân Mai
8    XLV         Công ty Cổ phần Xây lắp và Dịch vụ Sông Đà
9    XHC                  Công ty Cổ phần Xuân Hòa Việt Nam
Đã xuất file all_symbols.xlsx

In [6]:
# Lấy thông tin chi tiết cho tất cả mã theo sàn giao dịch
# Bao gồm cả mã đang và đã ngừng niêm yết
by_exchange = listing.symbols_by_exchange()
by_exchange.head()

# Xuất Excel
by_exchange.to_excel(
    "by_exchange.xlsx",
    index=False
)

In [7]:
# Lấy danh sách cổ phiếu được nhóm theo ngành ICB
by_industry = listing.symbols_by_industries()
by_industry.head()

# Xuất Excel
by_industry.to_excel(
    "by_industry.xlsx",
    index=False
)

print("Đã xuất file by_industry.xlsx")

Đã xuất file by_industry.xlsx

In [9]:
from vnstock import Listing, Trading
import pandas as pd

# =========================
# 1. Lấy danh sách cổ phiếu
# =========================

listing = Listing(source='VCI')

all_symbols = listing.all_symbols()

print(f"Tổng số mã: {len(all_symbols)}")
print(all_symbols.head())


# =========================
# 2. Chuyển mã CP thành list
# =========================

symbols = all_symbols['symbol'].tolist()

print(symbols[:10])


# =========================
# 3. Khởi tạo Trading VCI
# =========================

trading = Trading(source='VCI')


# =========================
# 4. Lấy bảng giá toàn bộ CP
#    chia batch để tránh request quá lớn
# =========================

batch_size = 100
price_data = []

for i in range(0, len(symbols), batch_size):
    
    batch = symbols[i:i + batch_size]
    
    try:
        df_batch = trading.price_board(batch)
        price_data.append(df_batch)
        print(f"Đã lấy {i + 1} - {min(i + batch_size, len(symbols))}")
        
    except Exception as e:
        print(f"Lỗi batch {i + 1}: {e}")


# Gộp lại thành một DataFrame
price_board = pd.concat(
    price_data,
    ignore_index=True
)

print(price_board.shape)
price_board.head()

Tổng số mã: 1753
  symbol                                         organ_name
0    YTC  Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...
1    YEG                     Công ty Cổ phần Tập đoàn Yeah1
2    YBM     Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái
3    YBC      Công ty Cổ phần Xi măng và Khoáng sản Yên Bái
4    XPH                    Công ty Cổ phần Xà phòng Hà Nội
['YTC', 'YEG', 'YBM', 'YBC', 'XPH', 'XMP', 'XMD', 'XMC', 'XLV', 'XHC']
Đã lấy 1 - 100
Đã lấy 101 - 200
Đã lấy 201 - 300
Đã lấy 301 - 400
Đã lấy 401 - 500
Đã lấy 501 - 600
Đã lấy 601 - 700
Đã lấy 701 - 800
Đã lấy 801 - 900
Đã lấy 901 - 1000
Đã lấy 1001 - 1100
Đã lấy 1101 - 1200
Đã lấy 1201 - 1300
Đã lấy 1301 - 1400
Đã lấy 1401 - 1500
Đã lấy 1501 - 1600
Đã lấy 1601 - 1700
Đã lấy 1701 - 1753
(1753, 118)

  listing                                                  \
   symbol  ceiling    floor ref_price stock_type exchange
0     YTC  24200.0  18000.0   21100.0      STOCK    UPCOM
1     YEG   7360.0   6400.0    6880.0      STOCK      HSX
2     YBM  10700.0   9300.0   10000.0      STOCK      HSX
3     YBC   8000.0   6000.0    7000.0      STOCK    UPCOM
4     XPH  15900.0  11900.0   13900.0      STOCK    UPCOM

                                                           \
                       trading_status trading_status_code
0                   TRADING_ACTIVATED                  20
1                   TRADING_ACTIVATED                  20
2  TRADING_FINANCIAL_REPORT_ACTIVATED                  32
3                   TRADING_ACTIVATED                  20
4                   TRADING_ACTIVATED                  20

                                        ...      bid_ask                \
  trading_status_group security_status  ... ask_10_price ask_10_volume
0                    2               N  ...          0.0           0.0
1                    2               N  ...          NaN           NaN
2                    3               N  ...          NaN           NaN
3                    2               N  ...          0.0           0.0
4                    2               N  ...          0.0           0.0

        match          bid_ask listing match               \
  market_code exchange    type     NaN  type closed_price
0         NaN      NaN     NaN     NaN   NaN          NaN
1         NaN      NaN     NaN     NaN   NaN          NaN
2         NaN      NaN     NaN     NaN   NaN          NaN
3         NaN      NaN     NaN     NaN   NaN          NaN
4         NaN      NaN     NaN     NaN   NaN          NaN


  total_accumulated_value total_accumulated_volume
0                     NaN                      NaN
1                     NaN                      NaN
2                     NaN                      NaN
3                     NaN                      NaN
4                     NaN                      NaN

[5 rows x 118 columns]

In [10]:
market_cap = price_board[[
    ('listing', 'symbol'),
    ('listing', 'exchange'),
    ('listing', 'organ_name'),
    ('listing', 'listed_share'),
    ('listing', 'ref_price'),
    ('match', 'match_price')
]].copy()

In [11]:
market_cap.columns = [
    'Mã CP',
    'Sàn',
    'Công ty',
    'SLCP niêm yết',
    'Giá tham chiếu',
    'Giá khớp'
]

market_cap.head()

,Mã CP,Sàn,Công ty,SLCP niêm yết,Giá tham chiếu,Giá khớp
0,YTC,UPCOM,Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...,9548000.0,21100.0,0
1,YEG,HSX,Công ty Cổ phần Tập đoàn Yeah1,205226448.0,6880.0,6950
2,YBM,HSX,Công ty Cổ phần Khoáng sản Công nghiệp Yên Bái,32174525.0,10000.0,0
3,YBC,UPCOM,Công ty Cổ phần Xi măng và Khoáng sản Yên Bái,11774180.0,7000.0,0
4,XPH,UPCOM,Công ty Cổ phần Xà phòng Hà Nội,12972475.0,13900.0,0

In [12]:
market_cap['Vốn hóa (VND)'] = (
    market_cap['Giá khớp']
    * market_cap['SLCP niêm yết']
)

market_cap['Vốn hóa (Tỷ đồng)'] = (
    market_cap['Vốn hóa (VND)']
    / 1_000_000_000
)

In [13]:
market_cap.head(20)

market_cap.to_excel(
    "market_cap_vci.xlsx",
    index=False
)

print("Đã xuất file market_cap_vci.xlsx")

Đã xuất file market_cap_vci.xlsx

In [15]:
# ============================================================
# VNSTOCK_CSDL
# TÍNH KHỐI LƯỢNG GIAO DỊCH TRUNG BÌNH 20 PHIÊN
# SOURCE: VCI
#
# Chức năng:
# 1. Tự lấy toàn bộ danh sách mã từ VCI
# 2. Lấy 20 phiên giao dịch gần nhất
# 3. Tính KLDG trung bình 20 phiên
# 4. Tự xử lý Rate Limit
# 5. Tự lưu checkpoint
# 6. Nếu bị dừng, chạy lại code sẽ tiếp tục
# 7. Xuất Excel cuối cùng
# ============================================================


# ============================================================
# 0. IMPORT THƯ VIỆN
# ============================================================

import os
import time
import pandas as pd

from pathlib import Path
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

from vnstock import Listing, Quote


# ============================================================
# 1. CẤU HÌNH
# ============================================================

# File lưu tạm trong quá trình chạy
CHECKPOINT_FILE = "KLDG_20_VCI_checkpoint.xlsx"
# True: lay lai toan bo du lieu, ke ca khi checkpoint cung ngay da co.
FORCE_REFRESH = False

# File Excel cuối cùng
FINAL_FILE = "KLDG_20_VCI.xlsx"


# ------------------------------------------------------------
# Delay giữa mỗi mã
#
# Community giới hạn 60 request/phút.
# Đặt 1.5 giây để không chạy sát giới hạn.
# ------------------------------------------------------------

REQUEST_DELAY = 1.5


# ------------------------------------------------------------
# Nếu vẫn gặp Rate Limit
# -> chờ 65 giây rồi thử lại CHÍNH MÃ ĐÓ
# ------------------------------------------------------------

RATE_LIMIT_WAIT = 65


# ------------------------------------------------------------
# Cứ 10 mã lưu checkpoint một lần
# ------------------------------------------------------------

CHECKPOINT_EVERY = 10


# ------------------------------------------------------------
# Lỗi thông thường: thử tối đa 3 lần
# ------------------------------------------------------------

MAX_RETRIES = 3



# ============================================================
# 2. XÁC ĐỊNH NGÀY GIAO DỊCH HOÀN THÀNH GẦN NHẤT
# ============================================================
#
# Mục đích:
# Không đưa khối lượng của phiên đang giao dịch dở
# vào KLDG trung bình 20 phiên.
#
# Trước 15:15 -> lấy dữ liệu đến ngày hôm qua
# Sau 15:15  -> cho phép lấy đến hôm nay
#
# Nếu ngày đó là cuối tuần/ngày nghỉ thì VCI sẽ trả
# phiên có dữ liệu gần nhất.
# ============================================================

now = datetime.now(
    ZoneInfo("Asia/Ho_Chi_Minh")
)

market_cutoff = now.replace(
    hour=15,
    minute=15,
    second=0,
    microsecond=0
)


if now < market_cutoff:

    end_date = (
        now.date()
        - timedelta(days=1)
    ).isoformat()

else:

    end_date = now.date().isoformat()

# Checkpoint chi duoc dung lai cho cung ngay ket thuc du lieu.
checkpoint_path = Path(CHECKPOINT_FILE)
CHECKPOINT_FILE = str(checkpoint_path.with_name(
    f"{checkpoint_path.stem}_{end_date}{checkpoint_path.suffix}"
))


print("=" * 70)

print(
    "Ngày kết thúc dữ liệu:",
    end_date
)

print("=" * 70)



# ============================================================
# 3. LẤY TOÀN BỘ DANH SÁCH MÃ TRỰC TIẾP TỪ VCI
# ============================================================

print()
print("Đang lấy danh sách mã từ VCI...")


listing = Listing(
    source="VCI"
)


symbols_df = listing.all_symbols()


# ------------------------------------------------------------
# Kiểm tra dữ liệu
# ------------------------------------------------------------

if symbols_df is None or symbols_df.empty:

    raise ValueError(
        "VCI không trả về danh sách mã."
    )


if "symbol" not in symbols_df.columns:

    raise ValueError(
        "Dữ liệu VCI không có cột symbol."
    )


# ------------------------------------------------------------
# Loại NA trước khi chuyển sang string
# ------------------------------------------------------------

symbols_df = symbols_df.dropna(
    subset=["symbol"]
).copy()


# ------------------------------------------------------------
# Chuẩn hóa symbol
# ------------------------------------------------------------

symbols_df["symbol"] = (
    symbols_df["symbol"]
    .astype(str)
    .str.strip()
    .str.upper()
)


# ------------------------------------------------------------
# Loại symbol rỗng
# ------------------------------------------------------------

symbols_df = symbols_df[
    symbols_df["symbol"] != ""
]


# ------------------------------------------------------------
# Loại trùng
# ------------------------------------------------------------

symbols_df = (
    symbols_df
    .drop_duplicates(
        subset=["symbol"],
        keep="first"
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# Tạo STT từ 1 -> 1753
# ------------------------------------------------------------

symbols_df.insert(
    0,
    "STT",
    range(
        1,
        len(symbols_df) + 1
    )
)


print()
print(
    f"Tổng số mã lấy từ VCI: "
    f"{len(symbols_df)}"
)


print()

print(
    symbols_df[
        ["STT", "symbol"]
    ].head(10)
)



# ============================================================
# 4. ĐỌC CHECKPOINT NẾU ĐÃ CÓ
# ============================================================

results = {}


if not FORCE_REFRESH and Path(CHECKPOINT_FILE).exists():

    print()
    print(
        "Phát hiện checkpoint cũ."
    )

    try:

        checkpoint_df = pd.read_excel(
            CHECKPOINT_FILE
        )


        if (
            checkpoint_df is not None
            and
            not checkpoint_df.empty
        ):

            for _, row in checkpoint_df.iterrows():

                symbol = str(
                    row["symbol"]
                ).strip().upper()


                results[symbol] = (
                    row.to_dict()
                )


        print(
            f"Checkpoint đang có: "
            f"{len(results)} mã."
        )


    except Exception as e:

        print(
            "Không đọc được checkpoint:"
        )

        print(e)

        print(
            "Chương trình sẽ chạy lại "
            "từ đầu."
        )

        results = {}


else:

    print()
    print(
        "Chưa có checkpoint."
    )

    print(
        "Bắt đầu từ mã đầu tiên."
    )



# ============================================================
# 5. XÁC ĐỊNH NHỮNG MÃ ĐÃ XỬ LÝ THÀNH CÔNG
# ============================================================
#
# Các mã này sẽ KHÔNG gọi API lại khi chạy lại chương trình.
# ============================================================

DONE_STATUS = {

    "OK",

    "THIEU_20_PHIEN",

    "KHONG_CO_DU_LIEU"
}


done_symbols = set()


for symbol, row in results.items():

    status = row.get(
        "Trang_thai"
    )

    if status in DONE_STATUS:

        done_symbols.add(
            symbol
        )


print()

print(
    f"Đã hoàn thành trước đó: "
    f"{len(done_symbols)} mã"
)

print(
    f"Còn phải xử lý: "
    f"{len(symbols_df) - len(done_symbols)} mã"
)



# ============================================================
# 6. HÀM LƯU CHECKPOINT
# ============================================================

def save_checkpoint(results_dict):

    if not results_dict:

        return


    checkpoint = pd.DataFrame(
        list(
            results_dict.values()
        )
    )


    if "STT" in checkpoint.columns:

        checkpoint = (
            checkpoint
            .sort_values("STT")
            .reset_index(drop=True)
        )


    # --------------------------------------------------------
    # Ghi file tạm trước
    # --------------------------------------------------------

    temp_file = (
        str(Path(CHECKPOINT_FILE).with_suffix(".tmp.xlsx"))
    )


    checkpoint.to_excel(
        temp_file,
        index=False,
        engine="openpyxl"
    )


    # --------------------------------------------------------
    # Sau khi ghi xong mới thay thế checkpoint cũ
    # --------------------------------------------------------

    os.replace(
        temp_file,
        CHECKPOINT_FILE
    )



# ============================================================
# 7. HÀM XỬ LÝ MỘT MÃ
# ============================================================

def get_kldg_20(
    symbol,
    stt
):

    retry = 0


    while True:

        try:

            # =================================================
            # KHỞI TẠO QUOTE
            # =================================================

            quote = Quote(
                symbol=symbol,
                source="VCI"
            )


            # =================================================
            # LẤY 20 BARS GẦN NHẤT
            # =================================================

            df = quote.history(

                end=end_date,

                length="20b",

                interval="1D"
            )


            # =================================================
            # KIỂM TRA KHÔNG CÓ DATA
            # =================================================

            if (
                df is None
                or
                df.empty
            ):

                return {

                    "STT": stt,

                    "symbol": symbol,

                    "KLDG_20": None,

                    "So_phien": 0,

                    "Tu_ngay": None,

                    "Den_ngay": None,

                    "Trang_thai":
                        "KHONG_CO_DU_LIEU"
                }


            # =================================================
            # COPY DATA
            # =================================================

            df = df.copy()


            # =================================================
            # KIỂM TRA CỘT
            # =================================================

            if "time" not in df.columns:

                raise ValueError(
                    "VCI không trả cột time"
                )


            if "volume" not in df.columns:

                raise ValueError(
                    "VCI không trả cột volume"
                )


            # =================================================
            # CHUYỂN TIME
            # =================================================

            df["time"] = pd.to_datetime(

                df["time"],

                errors="coerce"
            )


            # =================================================
            # CHUYỂN VOLUME SANG NUMBER
            # =================================================

            df["volume"] = pd.to_numeric(

                df["volume"],

                errors="coerce"
            )


            # =================================================
            # LOẠI DATA LỖI
            # =================================================

            df = df.dropna(

                subset=[
                    "time",
                    "volume"
                ]
            )


            # =================================================
            # SẮP XẾP THEO THỜI GIAN
            # =================================================

            df = df.sort_values(
                "time"
            )


            # =================================================
            # LOẠI NGÀY TRÙNG
            # =================================================

            df = df.drop_duplicates(

                subset=["time"],

                keep="last"
            )


            # =================================================
            # CHỈ GIỮ 20 PHIÊN CUỐI
            # =================================================

            df_20 = (
                df
                .tail(20)
                .copy()
            )


            so_phien = len(
                df_20
            )


            # =================================================
            # ĐỦ 20 PHIÊN
            # =================================================

            if so_phien == 20:

                kldg_20 = (
                    df_20["volume"]
                    .mean()
                )


                status = "OK"


            # =================================================
            # KHÔNG ĐỦ 20 PHIÊN
            # =================================================

            else:

                kldg_20 = None

                status = (
                    "THIEU_20_PHIEN"
                )


            # =================================================
            # KẾT QUẢ
            # =================================================

            return {

                "STT": stt,

                "symbol": symbol,

                "KLDG_20": (
                    round(kldg_20)
                    if pd.notna(kldg_20)
                    else None
                ),

                "So_phien": so_phien,

                "Tu_ngay": (
                    df_20["time"].min()
                    if so_phien > 0
                    else None
                ),

                "Den_ngay": (
                    df_20["time"].max()
                    if so_phien > 0
                    else None
                ),

                "Trang_thai":
                    status
            }



        # ====================================================
        # 8A. BẮT SYSTEMEXIT DO RATE LIMIT
        #
        # Đây là lỗi bạn vừa gặp.
        #
        # except Exception KHÔNG bắt được SystemExit.
        # ====================================================

        except SystemExit as e:

            print()
            print("=" * 70)

            print(
                f"⚠️ RATE LIMIT tại mã {symbol}"
            )

            print(
                f"Chờ {RATE_LIMIT_WAIT} giây..."
            )

            print("=" * 70)


            # -----------------------------------------------
            # Lưu tất cả kết quả trước khi chờ
            # -----------------------------------------------

            try:

                save_checkpoint(
                    results
                )

                print(
                    "✓ Đã lưu checkpoint."
                )

            except Exception as save_error:

                print(
                    "Không lưu được checkpoint:"
                )

                print(
                    save_error
                )


            # -----------------------------------------------
            # Chờ reset rate limit
            # -----------------------------------------------

            time.sleep(
                RATE_LIMIT_WAIT
            )


            print(
                f"Thử lại mã {symbol}..."
            )


            # -----------------------------------------------
            # Rất quan trọng:
            #
            # retry CHÍNH symbol hiện tại
            # KHÔNG chuyển sang mã kế tiếp
            # -----------------------------------------------

            continue



        # ====================================================
        # 8B. LỖI THÔNG THƯỜNG
        # ====================================================

        except Exception as e:

            retry += 1


            print(
                f"   ⚠ Lỗi {symbol}: {e}"
            )


            # -----------------------------------------------
            # Thử lại tối đa MAX_RETRIES
            # -----------------------------------------------

            if retry < MAX_RETRIES:

                print(
                    f"   Thử lại "
                    f"{retry}/{MAX_RETRIES}"
                )

                time.sleep(5)

                continue


            # -----------------------------------------------
            # Hết số lần retry
            #
            # Đánh dấu lỗi.
            # Lần chạy chương trình sau sẽ thử lại.
            # -----------------------------------------------

            return {

                "STT": stt,

                "symbol": symbol,

                "KLDG_20": None,

                "So_phien": None,

                "Tu_ngay": None,

                "Den_ngay": None,

                "Trang_thai":
                    f"LOI_CAN_THU_LAI: {str(e)}"
            }



# ============================================================
# 9. CHẠY TOÀN BỘ DANH SÁCH
# ============================================================

processed_this_run = 0


print()
print("=" * 70)
print("BẮT ĐẦU LẤY KLDG 20")
print("=" * 70)
print()


for _, row in symbols_df.iterrows():


    stt = int(
        row["STT"]
    )


    symbol = str(
        row["symbol"]
    )


    # ========================================================
    # BỎ QUA MÃ ĐÃ HOÀN THÀNH TRONG CHECKPOINT
    # ========================================================

    if symbol in done_symbols:

        continue


    print(
        f"[{stt}/{len(symbols_df)}] "
        f"Đang xử lý {symbol}..."
    )


    # ========================================================
    # LẤY KLDG 20
    # ========================================================

    result = get_kldg_20(

        symbol=symbol,

        stt=stt
    )


    # ========================================================
    # LƯU VÀO DICTIONARY
    # ========================================================

    results[symbol] = result


    processed_this_run += 1


    # ========================================================
    # IN KẾT QUẢ
    # ========================================================

    if (
        result["Trang_thai"]
        == "OK"
    ):

        print(

            "   ✓ KLDG 20 = "
            f"{result['KLDG_20']:,.0f}"

        )


    elif (
        result["Trang_thai"]
        == "THIEU_20_PHIEN"
    ):

        print(

            "   ⚠ Chỉ có "
            f"{result['So_phien']} phiên"

        )


    else:

        print(

            "   ⚠ "
            f"{result['Trang_thai']}"

        )


    # ========================================================
    # CỨ 10 MÃ LƯU CHECKPOINT
    # ========================================================

    if (
        processed_this_run
        % CHECKPOINT_EVERY
        == 0
    ):

        try:

            save_checkpoint(
                results
            )


            print(

                f"   💾 Checkpoint: "
                f"{len(results)} mã đã lưu"

            )


        except PermissionError:

            print()
            print(
                "⚠️ Không ghi được checkpoint."
            )

            print(
                "Hãy đóng file "
                "KLDG_20_VCI_checkpoint.xlsx "
                "nếu đang mở bằng Excel."
            )

            print()


    # ========================================================
    # DELAY GIỮA HAI REQUEST
    # ========================================================

    time.sleep(
        REQUEST_DELAY
    )



# ============================================================
# 10. LƯU CHECKPOINT LẦN CUỐI
# ============================================================

save_checkpoint(
    results
)



# ============================================================
# 11. CHUYỂN RESULTS THÀNH DATAFRAME
# ============================================================

df_result = pd.DataFrame(
    list(
        results.values()
    )
)


df_result = (
    df_result
    .sort_values("STT")
    .reset_index(drop=True)
)



# ============================================================
# 12. GHÉP VỚI DANH SÁCH MÃ GỐC
# ============================================================

result_columns = [

    "symbol",

    "KLDG_20",

    "So_phien",

    "Tu_ngay",

    "Den_ngay",

    "Trang_thai"
]


df_final = symbols_df.merge(

    df_result[
        result_columns
    ],

    on="symbol",

    how="left"
)



# ============================================================
# 13. CHUYỂN KLDG 20 THÀNH INTEGER
# ============================================================

df_final["KLDG_20"] = (

    pd.to_numeric(

        df_final["KLDG_20"],

        errors="coerce"

    )

    .round()

    .astype("Int64")
)



# ============================================================
# 14. TẠO SHEET KIỂM TRA
# ============================================================

df_check = df_final[

    df_final["Trang_thai"]
    != "OK"

].copy()



# ============================================================
# 15. XUẤT FILE EXCEL CUỐI
# ============================================================

with pd.ExcelWriter(

    FINAL_FILE,

    engine="openpyxl"

) as writer:


    # --------------------------------------------------------
    # Sheet 1: Toàn bộ mã
    # --------------------------------------------------------

    df_final.to_excel(

        writer,

        sheet_name="KLDG_20",

        index=False
    )


    # --------------------------------------------------------
    # Sheet 2: Các mã cần kiểm tra
    # --------------------------------------------------------

    df_check.to_excel(

        writer,

        sheet_name="Kiem_tra",

        index=False
    )



# ============================================================
# 16. THỐNG KÊ CUỐI
# ============================================================

total = len(
    df_final
)


ok_count = (

    df_final["Trang_thai"]
    .eq("OK")
    .sum()

)


thieu_count = (

    df_final["Trang_thai"]
    .eq("THIEU_20_PHIEN")
    .sum()

)


no_data_count = (

    df_final["Trang_thai"]
    .eq("KHONG_CO_DU_LIEU")
    .sum()

)


error_count = (

    df_final["Trang_thai"]
    .astype(str)
    .str.startswith(
        "LOI_CAN_THU_LAI"
    )
    .sum()

)


print()
print("=" * 70)

print("HOÀN THÀNH")

print("=" * 70)

print(
    f"Tổng số mã:             "
    f"{total}"
)

print(
    f"Đủ 20 phiên:            "
    f"{ok_count}"
)

print(
    f"Thiếu 20 phiên:         "
    f"{thieu_count}"
)

print(
    f"Không có dữ liệu:       "
    f"{no_data_count}"
)

print(
    f"Lỗi cần thử lại:        "
    f"{error_count}"
)

print()

print(
    f"File kết quả: "
    f"{FINAL_FILE}"
)

print(
    f"File checkpoint: "
    f"{CHECKPOINT_FILE}"
)

print("=" * 70)

======================================================================
Ngày kết thúc dữ liệu: 2026-09-16
======================================================================

Đang lấy danh sách mã từ VCI...

Tổng số mã lấy từ VCI: 1753

   STT symbol
0    1    YTC
1    2    YEG
2    3    YBM
3    4    YBC
4    5    XPH
5    6    XMP
6    7    XMD
7    8    XMC
8    9    XLV
9   10    XHC

Chưa có checkpoint.
Bắt đầu từ mã đầu tiên.

Đã hoàn thành trước đó: 0 mã
Còn phải xử lý: 1753 mã

======================================================================
BẮT ĐẦU LẤY KLDG 20
======================================================================

[1/1753] Đang xử lý YTC...
   ✓ KLDG 20 = 16
[2/1753] Đang xử lý YEG...
   ✓ KLDG 20 = 448,270
[3/1753] Đang xử lý YBM...
   ✓ KLDG 20 = 1,545
[4/1753] Đang xử lý YBC...
   ✓ KLDG 20 = 940
[5/1753] Đang xử lý XPH...
   ✓ KLDG 20 = 2,360
[6/1753] Đang xử lý XMP...
   ✓ KLDG 20 = 505
[7/1753] Đang xử lý XMD...
   ✓ KLDG 20 = 6,525
[8/1753] Đang xử lý XMC...
   ✓ KLDG 20 = 27,705
[9/1753] Đang xử lý XLV...
   ✓ KLDG 20 = 697
[10/1753] Đang xử lý XHC...
   ✓ KLDG 20 = 380
   💾 Checkpoint: 10 mã đã lưu
[11/1753] Đang xử lý XDH...
   ✓ KLDG 20 = 3,240
[12/1753] Đang xử lý XDC...
   ✓ KLDG 20 = 500
[13/1753] Đang xử lý X77...
   ✓ KLDG 20 = 0
[14/1753] Đang xử lý X26...
   ✓ KLDG 20 = 10
[15/1753] Đang xử lý X20...
   ✓ KLDG 20 = 1,891
[16/1753] Đang xử lý WTC...
   ✓ KLDG 20 = 1,570
[17/1753] Đang xử lý WSS...
   ✓ KLDG 20 = 19,760
[18/1753] Đang xử lý WSB...
   ✓ KLDG 20 = 510
[19/1753] Đang xử lý WCS...
   ✓ KLDG 20 = 330
[20/1753] Đang xử lý VXT...
   ✓ KLDG 20 = 2,130
   💾 Checkpoint: 20 mã đã lưu
[21/1753] Đang xử lý VXP...
   ✓ KLDG 20 = 0
[22/1753] Đang xử lý VXB...
   ✓ KLDG 20 = 210
[23/1753] Đang xử lý VWS...
   ✓ KLDG 20 = 1,560
[24/1753] Đang xử lý VW3...
   ✓ KLDG 20 = 1,795
[25/1753] Đang xử lý VVS...
   ✓ KLDG 20 = 108,100
[26/1753] Đang xử lý VVN...
   ✓ KLDG 20 = 2,800
[27/1753] Đang xử lý VUA...
   ✓ KLDG 20 = 795
[28/1753] Đang xử lý VTZ...
   ✓ KLDG 20 = 1,126,935
[29/1753] Đang xử lý VTX...
   ✓ KLDG 20 = 245
[30/1753] Đang xử lý VTV...
   ✓ KLDG 20 = 41,995
   💾 Checkpoint: 30 mã đã lưu
[31/1753] Đang xử lý VTS...
   ✓ KLDG 20 = 275
[32/1753] Đang xử lý VTR...
   ✓ KLDG 20 = 15,625
[33/1753] Đang xử lý VTQ...
   ✓ KLDG 20 = 1,070
[34/1753] Đang xử lý VTP...
   ✓ KLDG 20 = 603,080
[35/1753] Đang xử lý VTO...
   ✓ KLDG 20 = 91,675
[36/1753] Đang xử lý VTM...
   ✓ KLDG 20 = 0
[37/1753] Đang xử lý VTL...
   ✓ KLDG 20 = 2,460
[38/1753] Đang xử lý VTK...
   ✓ KLDG 20 = 3,960
[39/1753] Đang xử lý VTJ...
   ✓ KLDG 20 = 1,725
[40/1753] Đang xử lý VTI...
   ✓ KLDG 20 = 520
   💾 Checkpoint: 40 mã đã lưu
[41/1753] Đang xử lý VTH...
   ✓ KLDG 20 = 820
[42/1753] Đang xử lý VTG...
   ✓ KLDG 20 = 845
[43/1753] Đang xử lý VTE...
   ✓ KLDG 20 = 1,310
[44/1753] Đang xử lý VTD...
   ✓ KLDG 20 = 330,465
[45/1753] Đang xử lý VTC...
   ✓ KLDG 20 = 10,279
[46/1753] Đang xử lý VTB...
   ✓ KLDG 20 = 2,565
[47/1753] Đang xử lý VTA...
   ✓ KLDG 20 = 11,320
[48/1753] Đang xử lý VST...
   ✓ KLDG 20 = 18,425
[49/1753] Đang xử lý VSP...
   ✓ KLDG 20 = 0
[50/1753] Đang xử lý VSN...
   ✓ KLDG 20 = 78
   💾 Checkpoint: 50 mã đã lưu
[51/1753] Đang xử lý VSM...
   ✓ KLDG 20 = 1,060
[52/1753] Đang xử lý VSI...
   ✓ KLDG 20 = 2,220
[53/1753] Đang xử lý VSH...
   ✓ KLDG 20 = 5,923
[54/1753] Đang xử lý VSG...
   ✓ KLDG 20 = 1,680
[55/1753] Đang xử lý VSF...
   ✓ KLDG 20 = 34,215
[56/1753] Đang xử lý VSE...
   ✓ KLDG 20 = 4,775
[57/1753] Đang xử lý VSC...
   ✓ KLDG 20 = 10,002,765
[58/1753] Đang xử lý VSA...
   ✓ KLDG 20 = 2,200
[59/1753] Đang xử lý VRG...
   ✓ KLDG 20 = 1,490
[60/1753] Đang xử lý VRE...
   ✓ KLDG 20 = 5,152,550
   💾 Checkpoint: 60 mã đã lưu
[61/1753] Đang xử lý VRC...
   ✓ KLDG 20 = 31,995
[62/1753] Đang xử lý VQC...
   ✓ KLDG 20 = 725
[63/1753] Đang xử lý VPX...
   ✓ KLDG 20 = 794,420
[64/1753] Đang xử lý VPW...
   ✓ KLDG 20 = 0
[65/1753] Đang xử lý VPS...
   ✓ KLDG 20 = 7,345
[66/1753] Đang xử lý VPR...
   ✓ KLDG 20 = 1,978
[67/1753] Đang xử lý VPL...
   ✓ KLDG 20 = 846,375
[68/1753] Đang xử lý VPI...
   ✓ KLDG 20 = 2,290,520
[69/1753] Đang xử lý VPH...
   ✓ KLDG 20 = 23,420
[70/1753] Đang xử lý VPG...
   ✓ KLDG 20 = 191,220
   💾 Checkpoint: 70 mã đã lưu
[71/1753] Đang xử lý VPD...
   ✓ KLDG 20 = 4,785
[72/1753] Đang xử lý VPC...
   ✓ KLDG 20 = 12,805
[73/1753] Đang xử lý VPB...
   ✓ KLDG 20 = 17,966,340
[74/1753] Đang xử lý VPA...
   ✓ KLDG 20 = 1,300
[75/1753] Đang xử lý VOS...
   ✓ KLDG 20 = 516,465
[76/1753] Đang xử lý VOC...
   ✓ KLDG 20 = 24,995
[77/1753] Đang xử lý VNZ...
   ✓ KLDG 20 = 3,250
[78/1753] Đang xử lý VNY...
   ✓ KLDG 20 = 44,560
[79/1753] Đang xử lý VNX...
   ✓ KLDG 20 = 5
[80/1753] Đang xử lý VNT...
   ✓ KLDG 20 = 5,125
   💾 Checkpoint: 80 mã đã lưu
[81/1753] Đang xử lý VNS...
   ✓ KLDG 20 = 11,395
[82/1753] Đang xử lý VNR...
   ✓ KLDG 20 = 17,724
[83/1753] Đang xử lý VNP...
   ✓ KLDG 20 = 42,970
[84/1753] Đang xử lý VNM...
   ✓ KLDG 20 = 2,959,965
[85/1753] Đang xử lý VNL...
   ✓ KLDG 20 = 18,445
[86/1753] Đang xử lý VNI...
   ✓ KLDG 20 = 1,265
[87/1753] Đang xử lý VNH...
   ✓ KLDG 20 = 104,790
[88/1753] Đang xử lý VNG...
   ✓ KLDG 20 = 1,905
[89/1753] Đang xử lý VNF...
   ✓ KLDG 20 = 3,490
[90/1753] Đang xử lý VNE...
   ✓ KLDG 20 = 285,770
   💾 Checkpoint: 90 mã đã lưu
[91/1753] Đang xử lý VND...
   ✓ KLDG 20 = 9,711,900
[92/1753] Đang xử lý VNC...
   ✓ KLDG 20 = 1,775
[93/1753] Đang xử lý VNB...
   ✓ KLDG 20 = 87,525
[94/1753] Đang xử lý VNA...
   ✓ KLDG 20 = 1,340
[95/1753] Đang xử lý VMT...
   ✓ KLDG 20 = 565
[96/1753] Đang xử lý VMS...
   ✓ KLDG 20 = 15,005
[97/1753] Đang xử lý VMK...
   ✓ KLDG 20 = 90
[98/1753] Đang xử lý VMI...
   ✓ KLDG 20 = 49,160
[99/1753] Đang xử lý VMG...
   ✓ KLDG 20 = 9,435
[100/1753] Đang xử lý VMD...
   ✓ KLDG 20 = 980
   💾 Checkpoint: 100 mã đã lưu
[101/1753] Đang xử lý VMC...
   ✓ KLDG 20 = 1,760
[102/1753] Đang xử lý VMA...
   ✓ KLDG 20 = 0
[103/1753] Đang xử lý VLW...
   ✓ KLDG 20 = 194
[104/1753] Đang xử lý VLS...
   ✓ KLDG 20 = 7,830
[105/1753] Đang xử lý VLP...
   ✓ KLDG 20 = 0
[106/1753] Đang xử lý VLG...
   ✓ KLDG 20 = 1,065
[107/1753] Đang xử lý VLF...
   ✓ KLDG 20 = 101,760
[108/1753] Đang xử lý VLC...
   ✓ KLDG 20 = 26,395
[109/1753] Đang xử lý VLB...
   ✓ KLDG 20 = 19,970
[110/1753] Đang xử lý VLA...
   ✓ KLDG 20 = 545
   💾 Checkpoint: 110 mã đã lưu
[111/1753] Đang xử lý VKP...
   ✓ KLDG 20 = 0
[112/1753] Đang xử lý VKD...
   ✓ KLDG 20 = 0
[113/1753] Đang xử lý VKC...
   ✓ KLDG 20 = 310,855
[114/1753] Đang xử lý VJC...
   ✓ KLDG 20 = 1,187,755
[115/1753] Đang xử lý VIX...
   ✓ KLDG 20 = 40,530,636
[116/1753] Đang xử lý VIW...
   ✓ KLDG 20 = 96,090
[117/1753] Đang xử lý VIT...
   ✓ KLDG 20 = 18,515
[118/1753] Đang xử lý VIS...
   ⚠ Lỗi VIS: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 1/3
   ⚠ Lỗi VIS: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 2/3
   ⚠ Lỗi VIS: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   ⚠ LOI_CAN_THU_LAI: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
[119/1753] Đang xử lý VIR...
   ✓ KLDG 20 = 1,990
[120/1753] Đang xử lý VIP...
   ✓ KLDG 20 = 41,445
   💾 Checkpoint: 120 mã đã lưu
[121/1753] Đang xử lý VIN...
   ✓ KLDG 20 = 123
[122/1753] Đang xử lý VIM...
   ✓ KLDG 20 = 619
[123/1753] Đang xử lý VIH...
   ✓ KLDG 20 = 1,215
[124/1753] Đang xử lý VIG...
   ✓ KLDG 20 = 37,555
[125/1753] Đang xử lý VIF...
   ✓ KLDG 20 = 9,315
[126/1753] Đang xử lý VIE...
   ✓ KLDG 20 = 675
[127/1753] Đang xử lý VID...
   ✓ KLDG 20 = 2,170
[128/1753] Đang xử lý VIC...
   ✓ KLDG 20 = 5,948,200
[129/1753] Đang xử lý VIB...
   ✓ KLDG 20 = 4,665,413
[130/1753] Đang xử lý VHM...
   ✓ KLDG 20 = 7,589,868
   💾 Checkpoint: 130 mã đã lưu
[131/1753] Đang xử lý VHL...
   ✓ KLDG 20 = 895
[132/1753] Đang xử lý VHI...
   ⚠ Lỗi VHI: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 1/3
   ⚠ Lỗi VHI: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 2/3
   ⚠ Lỗi VHI: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   ⚠ LOI_CAN_THU_LAI: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
[133/1753] Đang xử lý VHH...
   ✓ KLDG 20 = 730
[134/1753] Đang xử lý VHG...
   ✓ KLDG 20 = 79,300
[135/1753] Đang xử lý VHF...
   ✓ KLDG 20 = 1,430
[136/1753] Đang xử lý VHE...
   ✓ KLDG 20 = 87,530
[137/1753] Đang xử lý VHD...
   ✓ KLDG 20 = 3,150
[138/1753] Đang xử lý VHC...
   ✓ KLDG 20 = 283,810
[139/1753] Đang xử lý VGV...
   ✓ KLDG 20 = 4,120
[140/1753] Đang xử lý VGT...
   ✓ KLDG 20 = 283,940
   💾 Checkpoint: 140 mã đã lưu
[141/1753] Đang xử lý VGS...
   ✓ KLDG 20 = 94,745
[142/1753] Đang xử lý VGR...
   ✓ KLDG 20 = 5,974
[143/1753] Đang xử lý VGP...
   ✓ KLDG 20 = 26,500
[144/1753] Đang xử lý VGL...
   ✓ KLDG 20 = 132
[145/1753] Đang xử lý VGI...
   ✓ KLDG 20 = 284,849
[146/1753] Đang xử lý VGG...
   ✓ KLDG 20 = 1,030
[147/1753] Đang xử lý VGC...
   ✓ KLDG 20 = 308,230
[148/1753] Đang xử lý VFS...
   ✓ KLDG 20 = 732,245
[149/1753] Đang xử lý VFR...
   ✓ KLDG 20 = 1,275
[150/1753] Đang xử lý VFG...
   ✓ KLDG 20 = 1,705
   💾 Checkpoint: 150 mã đã lưu
[151/1753] Đang xử lý VFC...
   ✓ KLDG 20 = 600
[152/1753] Đang xử lý VET...
   ✓ KLDG 20 = 780
[153/1753] Đang xử lý VES...
   ✓ KLDG 20 = 1,505
[154/1753] Đang xử lý VEF...
   ✓ KLDG 20 = 4,085
[155/1753] Đang xử lý VEC...
   ✓ KLDG 20 = 6,410
[156/1753] Đang xử lý VEA...
   ✓ KLDG 20 = 217,615
[157/1753] Đang xử lý VE9...
   ✓ KLDG 20 = 6,420
[158/1753] Đang xử lý VE8...
   ✓ KLDG 20 = 4,385
[159/1753] Đang xử lý VE4...
   ✓ KLDG 20 = 10
[160/1753] Đang xử lý VE3...
   ✓ KLDG 20 = 7,675
   💾 Checkpoint: 160 mã đã lưu
[161/1753] Đang xử lý VE2...
   ✓ KLDG 20 = 260
[162/1753] Đang xử lý VE1...
   ✓ KLDG 20 = 2,740
[163/1753] Đang xử lý VDT...
   ✓ KLDG 20 = 60
[164/1753] Đang xử lý VDS...
   ✓ KLDG 20 = 668,620
[165/1753] Đang xử lý VDP...
   ✓ KLDG 20 = 4,695
[166/1753] Đang xử lý VDN...
   ✓ KLDG 20 = 267
[167/1753] Đang xử lý VDM...
   ⚠ Lỗi VDM: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 1/3
   ⚠ Lỗi VDM: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 2/3
   ⚠ Lỗi VDM: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   ⚠ LOI_CAN_THU_LAI: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
[168/1753] Đang xử lý VDL...
   ✓ KLDG 20 = 11,240
[169/1753] Đang xử lý VDG...
   ✓ KLDG 20 = 1,105
[170/1753] Đang xử lý VDB...
   ✓ KLDG 20 = 0
   💾 Checkpoint: 170 mã đã lưu
[171/1753] Đang xử lý VCX...
   ✓ KLDG 20 = 4,965
[172/1753] Đang xử lý VCW...
   ✓ KLDG 20 = 8,365
[173/1753] Đang xử lý VCT...
   ✓ KLDG 20 = 70
[174/1753] Đang xử lý VCS...
   ✓ KLDG 20 = 43,135
[175/1753] Đang xử lý VCR...
   ✓ KLDG 20 = 1,820
[176/1753] Đang xử lý VCP...
   ✓ KLDG 20 = 11,055
[177/1753] Đang xử lý VCM...
   ✓ KLDG 20 = 3,965
[178/1753] Đang xử lý VCK...
   ✓ KLDG 20 = 2,037,945
[179/1753] Đang xử lý VCI...
   ✓ KLDG 20 = 9,469,500
[180/1753] Đang xử lý VCG...
   ✓ KLDG 20 = 2,117,405
   💾 Checkpoint: 180 mã đã lưu
[181/1753] Đang xử lý VCF...
   ✓ KLDG 20 = 225
[182/1753] Đang xử lý VCE...
   ✓ KLDG 20 = 0
[183/1753] Đang xử lý VCC...
   ✓ KLDG 20 = 14,440
[184/1753] Đang xử lý VCB...
   ✓ KLDG 20 = 4,666,590
[185/1753] Đang xử lý VCA...
   ✓ KLDG 20 = 695
[186/1753] Đang xử lý VC9...
   ✓ KLDG 20 = 16,825
[187/1753] Đang xử lý VC7...
   ✓ KLDG 20 = 55,740
[188/1753] Đang xử lý VC6...
   ✓ KLDG 20 = 1,516
[189/1753] Đang xử lý VC5...
   ✓ KLDG 20 = 1,540
[190/1753] Đang xử lý VC3...
   ✓ KLDG 20 = 1,200,181
   💾 Checkpoint: 190 mã đã lưu
[191/1753] Đang xử lý VC2...
   ✓ KLDG 20 = 58,820
[192/1753] Đang xử lý VC1...
   ✓ KLDG 20 = 635
[193/1753] Đang xử lý VBT...
   ✓ KLDG 20 = 1,385
[194/1753] Đang xử lý VBH...
   ✓ KLDG 20 = 870
[195/1753] Đang xử lý VBG...
   ✓ KLDG 20 = 35
[196/1753] Đang xử lý VBC...
   ✓ KLDG 20 = 300
[197/1753] Đang xử lý VBB...
   ✓ KLDG 20 = 38,310
[198/1753] Đang xử lý VAV...
   ✓ KLDG 20 = 70
[199/1753] Đang xử lý VAT...
   ✓ KLDG 20 = 56,370
[200/1753] Đang xử lý VAF...
   ✓ KLDG 20 = 556
   💾 Checkpoint: 200 mã đã lưu
[201/1753] Đang xử lý VAB...
   ✓ KLDG 20 = 454,131
[202/1753] Đang xử lý V68...
   ⚠ Chỉ có 19 phiên
[203/1753] Đang xử lý V21...
   ✓ KLDG 20 = 2,635
[204/1753] Đang xử lý V15...
   ✓ KLDG 20 = 0
[205/1753] Đang xử lý V12...
   ✓ KLDG 20 = 1,620
[206/1753] Đang xử lý V11...
   ✓ KLDG 20 = 16,990
[207/1753] Đang xử lý UXC...
   ✓ KLDG 20 = 1,630
[208/1753] Đang xử lý UTT...
   ⚠ Lỗi UTT: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 1/3
   ⚠ Lỗi UTT: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 2/3
   ⚠ Lỗi UTT: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   ⚠ LOI_CAN_THU_LAI: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
[209/1753] Đang xử lý USD...
   ✓ KLDG 20 = 865
[210/1753] Đang xử lý USC...
   ✓ KLDG 20 = 2,540
   💾 Checkpoint: 210 mã đã lưu
[211/1753] Đang xử lý UPS...
   ✓ KLDG 20 = 245
[212/1753] Đang xử lý UPH...
   ✓ KLDG 20 = 370
[213/1753] Đang xử lý UPC...
   ✓ KLDG 20 = 635
[214/1753] Đang xử lý UNI...
   ✓ KLDG 20 = 1,995
[215/1753] Đang xử lý UMC...
   ✓ KLDG 20 = 0
[216/1753] Đang xử lý ULG...
   ✓ KLDG 20 = 3,905
[217/1753] Đang xử lý UIC...
   ✓ KLDG 20 = 1,865
[218/1753] Đang xử lý UEM...
   ✓ KLDG 20 = 300
[219/1753] Đang xử lý UDL...
   ✓ KLDG 20 = 94
[220/1753] Đang xử lý UDJ...
   ✓ KLDG 20 = 12,235
   💾 Checkpoint: 220 mã đã lưu
[221/1753] Đang xử lý UDC...
   ✓ KLDG 20 = 19,330
[222/1753] Đang xử lý UCT...
   ✓ KLDG 20 = 2,190
[223/1753] Đang xử lý TYA...
   ✓ KLDG 20 = 4,565
[224/1753] Đang xử lý TXM...
   ✓ KLDG 20 = 3,575
[225/1753] Đang xử lý TW3...
   ✓ KLDG 20 = 0
[226/1753] Đang xử lý TVW...
   ✓ KLDG 20 = 625
[227/1753] Đang xử lý TVT...
   ✓ KLDG 20 = 2,265
[228/1753] Đang xử lý TVS...
   ✓ KLDG 20 = 146,217
[229/1753] Đang xử lý TVP...
   ✓ KLDG 20 = 8,820
[230/1753] Đang xử lý TVN...
   ✓ KLDG 20 = 469,575
   💾 Checkpoint: 230 mã đã lưu
[231/1753] Đang xử lý TVM...
   ✓ KLDG 20 = 79
[232/1753] Đang xử lý TVH...
   ✓ KLDG 20 = 46
[233/1753] Đang xử lý TVG...
   ✓ KLDG 20 = 220
[234/1753] Đang xử lý TVD...
   ✓ KLDG 20 = 23,225
[235/1753] Đang xử lý TVC...
   ✓ KLDG 20 = 6,990
[236/1753] Đang xử lý TVB...
   ✓ KLDG 20 = 6,930
[237/1753] Đang xử lý TVA...
   ✓ KLDG 20 = 14
[238/1753] Đang xử lý TV6...
   ✓ KLDG 20 = 225
[239/1753] Đang xử lý TV4...
   ✓ KLDG 20 = 11,420
[240/1753] Đang xử lý TV3...
   ✓ KLDG 20 = 1,131
   💾 Checkpoint: 240 mã đã lưu
[241/1753] Đang xử lý TV2...
   ✓ KLDG 20 = 90,440
[242/1753] Đang xử lý TV1...
   ✓ KLDG 20 = 19,435
[243/1753] Đang xử lý TUG...
   ✓ KLDG 20 = 535
[244/1753] Đang xử lý TTZ...
   ✓ KLDG 20 = 0
[245/1753] Đang xử lý TTT...
   ✓ KLDG 20 = 635
[246/1753] Đang xử lý TTS...
   ✓ KLDG 20 = 330
[247/1753] Đang xử lý TTP...
   ✓ KLDG 20 = 2,370
[248/1753] Đang xử lý TTN...
   ✓ KLDG 20 = 9,205
[249/1753] Đang xử lý TTL...
   ✓ KLDG 20 = 2,120
[250/1753] Đang xử lý TTH...
   ✓ KLDG 20 = 274,500
   💾 Checkpoint: 250 mã đã lưu
[251/1753] Đang xử lý TTG...
   ✓ KLDG 20 = 33,745
[252/1753] Đang xử lý TTF...
   ✓ KLDG 20 = 727,985
[253/1753] Đang xử lý TTE...
   ✓ KLDG 20 = 285
[254/1753] Đang xử lý TTD...
   ✓ KLDG 20 = 245
[255/1753] Đang xử lý TTC...
   ✓ KLDG 20 = 3,100
[256/1753] Đang xử lý TTB...
   ✓ KLDG 20 = 0
[257/1753] Đang xử lý TTA...
   ✓ KLDG 20 = 206,310
[258/1753] Đang xử lý TT6...
   ✓ KLDG 20 = 3,415
[259/1753] Đang xử lý TST...
   ✓ KLDG 20 = 25,060
[260/1753] Đang xử lý TSJ...
   ✓ KLDG 20 = 97
   💾 Checkpoint: 260 mã đã lưu
[261/1753] Đang xử lý TSG...
   ✓ KLDG 20 = 0
[262/1753] Đang xử lý TSD...
   ✓ KLDG 20 = 1,575
[263/1753] Đang xử lý TSC...
   ✓ KLDG 20 = 107,010
[264/1753] Đang xử lý TSB...
   ✓ KLDG 20 = 11,895
[265/1753] Đang xử lý TSA...
   ✓ KLDG 20 = 60,345
[266/1753] Đang xử lý TS5...
   ⚠ Lỗi TS5: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 1/3
   ⚠ Lỗi TS5: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 2/3
   ⚠ Lỗi TS5: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   ⚠ LOI_CAN_THU_LAI: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
[267/1753] Đang xử lý TS4...
   ✓ KLDG 20 = 0
[268/1753] Đang xử lý TS3...
   ✓ KLDG 20 = 11,095
[269/1753] Đang xử lý TRV...
   ✓ KLDG 20 = 30,825
[270/1753] Đang xử lý TRT...
   ✓ KLDG 20 = 2,915
   💾 Checkpoint: 270 mã đã lưu
[271/1753] Đang xử lý TRS...
   ✓ KLDG 20 = 155
[272/1753] Đang xử lý TRC...
   ✓ KLDG 20 = 176,792
[273/1753] Đang xử lý TRA...
   ✓ KLDG 20 = 3,410
[274/1753] Đang xử lý TR1...
   ✓ KLDG 20 = 950
[275/1753] Đang xử lý TQW...
   ✓ KLDG 20 = 0
[276/1753] Đang xử lý TQN...
   ✓ KLDG 20 = 0
[277/1753] Đang xử lý TPS...
   ✓ KLDG 20 = 220
[278/1753] Đang xử lý TPP...
   ✓ KLDG 20 = 2,415
[279/1753] Đang xử lý TPH...
   ✓ KLDG 20 = 1,741
[280/1753] Đang xử lý TPC...
   ✓ KLDG 20 = 66,480
   💾 Checkpoint: 280 mã đã lưu
[281/1753] Đang xử lý TPB...
   ✓ KLDG 20 = 6,494,035
[282/1753] Đang xử lý TOW...
   ✓ KLDG 20 = 333
[283/1753] Đang xử lý TOT...
   ✓ KLDG 20 = 790
[284/1753] Đang xử lý TOS...
   ✓ KLDG 20 = 12,885
[285/1753] Đang xử lý TOP...
   ✓ KLDG 20 = 61,170
[286/1753] Đang xử lý TNW...
   ✓ KLDG 20 = 1,090
[287/1753] Đang xử lý TNV...
   ✓ KLDG 20 = 12,770
[288/1753] Đang xử lý TNT...
   ✓ KLDG 20 = 36,290
[289/1753] Đang xử lý TNS...
   ✓ KLDG 20 = 13,955
[290/1753] Đang xử lý TNP...
   ✓ KLDG 20 = 145
   💾 Checkpoint: 290 mã đã lưu
[291/1753] Đang xử lý TNM...
   ✓ KLDG 20 = 0
[292/1753] Đang xử lý TNI...
   ✓ KLDG 20 = 776,205
[293/1753] Đang xử lý TNH...
   ✓ KLDG 20 = 96,960
[294/1753] Đang xử lý TNG...
   ✓ KLDG 20 = 330,465
[295/1753] Đang xử lý TNC...
   ✓ KLDG 20 = 560
[296/1753] Đang xử lý TNB...
   ✓ KLDG 20 = 535
[297/1753] Đang xử lý TNA...
   ✓ KLDG 20 = 140,205
[298/1753] Đang xử lý TN1...
   ✓ KLDG 20 = 1,626
[299/1753] Đang xử lý TMX...
   ✓ KLDG 20 = 1,760
[300/1753] Đang xử lý TMW...
   ✓ KLDG 20 = 0
   💾 Checkpoint: 300 mã đã lưu
[301/1753] Đang xử lý TMT...
   ✓ KLDG 20 = 8,635
[302/1753] Đang xử lý TMS...
   ✓ KLDG 20 = 1,035
[303/1753] Đang xử lý TMP...
   ✓ KLDG 20 = 1,635
[304/1753] Đang xử lý TMG...
   ✓ KLDG 20 = 824
[305/1753] Đang xử lý TMC...
   ✓ KLDG 20 = 3,120
[306/1753] Đang xử lý TMB...
   ✓ KLDG 20 = 1,060
[307/1753] Đang xử lý TLT...
   ✓ KLDG 20 = 2,025
[308/1753] Đang xử lý TLP...
   ✓ KLDG 20 = 60,725
[309/1753] Đang xử lý TLI...
   ✓ KLDG 20 = 1,525
[310/1753] Đang xử lý TLH...
   ✓ KLDG 20 = 105,345
   💾 Checkpoint: 310 mã đã lưu
[311/1753] Đang xử lý TLG...
   ✓ KLDG 20 = 149,385
[312/1753] Đang xử lý TLD...
   ✓ KLDG 20 = 146,875
[313/1753] Đang xử lý TL4...
   ✓ KLDG 20 = 10,710
[314/1753] Đang xử lý TKU...
   ✓ KLDG 20 = 1,330
[315/1753] Đang xử lý TKG...
   ✓ KLDG 20 = 65,854
[316/1753] Đang xử lý TKC...
   ✓ KLDG 20 = 0
[317/1753] Đang xử lý TKA...
   ✓ KLDG 20 = 0
[318/1753] Đang xử lý TJC...
   ✓ KLDG 20 = 2,725
[319/1753] Đang xử lý TIX...
   ✓ KLDG 20 = 1,000
[320/1753] Đang xử lý TIS...
   ✓ KLDG 20 = 4,080
   💾 Checkpoint: 320 mã đã lưu
[321/1753] Đang xử lý TIP...
   ✓ KLDG 20 = 21,966
[322/1753] Đang xử lý TIN...
   ✓ KLDG 20 = 19,810
[323/1753] Đang xử lý TIG...
   ✓ KLDG 20 = 675,360
[324/1753] Đang xử lý TIE...
   ✓ KLDG 20 = 1,760
[325/1753] Đang xử lý TID...
   ✓ KLDG 20 = 2,145
[326/1753] Đang xử lý THW...
   ✓ KLDG 20 = 478
[327/1753] Đang xử lý THU...
   ✓ KLDG 20 = 755
[328/1753] Đang xử lý THT...
   ✓ KLDG 20 = 10,085

In [18]:
# ============================================================
# VNSTOCK_CSDL
# GTGD TRUNG BÌNH 20 PHIÊN GẦN NHẤT
#
# SOURCE: VCI
# PACKAGE: vnstock Community
#
# ĐƠN VỊ OUTPUT:
# GTGD_20 = tỷ đồng / phiên
#
# LƯU Ý:
# Đây là GTGD ƯỚC TÍNH:
#
# GTGD ngày ≈ Close × Volume
#
# ============================================================


# ============================================================
# 0. IMPORT
# ============================================================

import os
import time
import pandas as pd

from pathlib import Path
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

from vnstock import Listing, Quote


# ============================================================
# 1. CẤU HÌNH
# ============================================================

CHECKPOINT_FILE = "GTGD_20_VCI_checkpoint.xlsx"
# True: lay lai toan bo du lieu, ke ca khi checkpoint cung ngay da co.
FORCE_REFRESH = False

FINAL_FILE = "GTGD_20_VCI.xlsx"


# ------------------------------------------------------------
# COMMUNITY LIMIT:
# 60 requests/phút
#
# 2.5 giây/request
# ≈ tối đa khoảng 24 mã/phút
#
# Có khoảng đệm khá lớn so với giới hạn 60.
# ------------------------------------------------------------

REQUEST_DELAY = 2.5


# Nếu vẫn gặp Rate Limit
# chờ 65 giây

RATE_LIMIT_WAIT = 65


# Cứ 10 mã lưu checkpoint

CHECKPOINT_EVERY = 10


# Retry khi lỗi thông thường

MAX_RETRIES = 3


# ============================================================
# 2. XÁC ĐỊNH NGÀY KẾT THÚC
# ============================================================
#
# Tránh lấy phiên hiện tại nếu thị trường chưa đóng cửa.
# ============================================================

now = datetime.now(
    ZoneInfo("Asia/Ho_Chi_Minh")
)


market_cutoff = now.replace(
    hour=15,
    minute=15,
    second=0,
    microsecond=0
)


if now < market_cutoff:

    end_date = (
        now.date()
        - timedelta(days=1)
    ).isoformat()

else:

    end_date = (
        now.date()
    ).isoformat()

# Checkpoint chi duoc dung lai cho cung ngay ket thuc du lieu.
checkpoint_path = Path(CHECKPOINT_FILE)
CHECKPOINT_FILE = str(checkpoint_path.with_name(
    f"{checkpoint_path.stem}_{end_date}{checkpoint_path.suffix}"
))


print("=" * 70)

print(
    "Ngày kết thúc dữ liệu:",
    end_date
)

print("=" * 70)


# ============================================================
# 3. LẤY DANH SÁCH MÃ TỪ VCI
# ============================================================

print()

print(
    "Đang lấy danh sách mã từ VCI..."
)


listing = Listing(
    source="VCI"
)


symbols_df = (
    listing.all_symbols()
)


# ============================================================
# 4. KIỂM TRA DỮ LIỆU
# ============================================================

if (
    symbols_df is None
    or
    symbols_df.empty
):

    raise ValueError(
        "VCI không trả về danh sách mã."
    )


if "symbol" not in symbols_df.columns:

    raise ValueError(
        "Không tìm thấy cột symbol."
    )


# ============================================================
# 5. CLEAN SYMBOL
# ============================================================

symbols_df = (

    symbols_df

    .dropna(
        subset=["symbol"]
    )

    .copy()
)


symbols_df["symbol"] = (

    symbols_df["symbol"]

    .astype(str)

    .str.strip()

    .str.upper()
)


# Loại symbol rỗng

symbols_df = symbols_df[

    symbols_df["symbol"] != ""

]


# Loại trùng

symbols_df = (

    symbols_df

    .drop_duplicates(
        subset=["symbol"],
        keep="first"
    )

    .reset_index(
        drop=True
    )
)


# ============================================================
# 6. THÊM STT
# ============================================================

symbols_df.insert(

    0,

    "STT",

    range(
        1,
        len(symbols_df) + 1
    )
)


print()

print(
    f"Tổng số mã lấy từ VCI: "
    f"{len(symbols_df)}"
)


print()

print(

    symbols_df[
        ["STT", "symbol"]
    ].head(10)

)


# ============================================================
# 7. ĐỌC CHECKPOINT
# ============================================================

results = {}


if not FORCE_REFRESH and Path(
    CHECKPOINT_FILE
).exists():

    print()

    print(
        "Phát hiện checkpoint GTGD cũ."
    )


    try:

        checkpoint_df = (
            pd.read_excel(
                CHECKPOINT_FILE
            )
        )


        if not checkpoint_df.empty:

            for _, row in (
                checkpoint_df.iterrows()
            ):

                symbol = str(
                    row["symbol"]
                ).strip().upper()


                results[symbol] = (
                    row.to_dict()
                )


        print(
            f"Checkpoint đang có: "
            f"{len(results)} mã"
        )


    except Exception as e:

        print(
            "Không đọc được checkpoint:"
        )

        print(e)

        results = {}


else:

    print()

    print(
        "Chưa có checkpoint GTGD."
    )

    print(
        "Bắt đầu từ mã đầu tiên."
    )


# ============================================================
# 8. XÁC ĐỊNH NHỮNG MÃ ĐÃ LÀM XONG
# ============================================================

DONE_STATUS = {

    "OK",

    "THIEU_20_PHIEN",

    "KHONG_CO_DU_LIEU"
}


done_symbols = set()


for symbol, row in (
    results.items()
):

    if (
        row.get("Trang_thai")
        in DONE_STATUS
    ):

        done_symbols.add(
            symbol
        )


print()

print(
    f"Đã hoàn thành trước đó: "
    f"{len(done_symbols)} mã"
)


print(
    f"Còn phải xử lý: "
    f"{len(symbols_df) - len(done_symbols)} mã"
)


# ============================================================
# 9. HÀM LƯU CHECKPOINT
# ============================================================

def save_checkpoint(
    results_dict
):

    if not results_dict:

        return


    checkpoint = pd.DataFrame(

        list(
            results_dict.values()
        )
    )


    if "STT" in checkpoint.columns:

        checkpoint = (

            checkpoint

            .sort_values("STT")

            .reset_index(
                drop=True
            )
        )


    # --------------------------------------------------------
    # Ghi vào file tạm trước
    # --------------------------------------------------------

    temp_file = (
        str(Path(CHECKPOINT_FILE).with_suffix(".tmp.xlsx"))
    )


    checkpoint.to_excel(

        temp_file,

        index=False,

        engine="openpyxl"
    )


    # --------------------------------------------------------
    # Sau đó mới thay checkpoint cũ
    # --------------------------------------------------------

    os.replace(

        temp_file,

        CHECKPOINT_FILE
    )


# ============================================================
# 10. HÀM LẤY GTGD 20 CHO 1 MÃ
# ============================================================

def get_gtgd_20(
    symbol,
    stt
):

    retry = 0


    while True:

        try:

            # =================================================
            # KHỞI TẠO QUOTE
            # SOURCE = VCI
            # =================================================

            quote = Quote(

                symbol=symbol,

                source="VCI"
            )


            # =================================================
            # LẤY 20 PHIÊN GẦN NHẤT
            # =================================================

            df = quote.history(

                end=end_date,

                length="20b",

                interval="1D"
            )


            # =================================================
            # KHÔNG CÓ DATA
            # =================================================

            if (
                df is None
                or
                df.empty
            ):

                return {

                    "STT": stt,

                    "symbol": symbol,

                    "GTGD_20": None,

                    "So_phien": 0,

                    "Tu_ngay": None,

                    "Den_ngay": None,

                    "Trang_thai":
                        "KHONG_CO_DU_LIEU"
                }


            # =================================================
            # COPY
            # =================================================

            df = df.copy()


            # =================================================
            # KIỂM TRA CỘT
            # =================================================

            required_columns = [

                "time",

                "close",

                "volume"
            ]


            for col in required_columns:

                if col not in df.columns:

                    raise ValueError(

                        f"VCI không trả cột {col}"

                    )


            # =================================================
            # CONVERT TIME
            # =================================================

            df["time"] = pd.to_datetime(

                df["time"],

                errors="coerce"
            )


            # =================================================
            # CONVERT CLOSE
            # ============================================================

            df["close"] = pd.to_numeric(

                df["close"],

                errors="coerce"
            )


            # =================================================
            # CONVERT VOLUME
            # ============================================================

            df["volume"] = pd.to_numeric(

                df["volume"],

                errors="coerce"
            )


            # =================================================
            # LOẠI DATA LỖI
            # ============================================================

            df = df.dropna(

                subset=[

                    "time",

                    "close",

                    "volume"

                ]
            )


            # =================================================
            # SORT DATE
            # ============================================================

            df = df.sort_values(
                "time"
            )


            # =================================================
            # LOẠI NGÀY TRÙNG
            # ============================================================

            df = df.drop_duplicates(

                subset=["time"],

                keep="last"
            )


            # =================================================
            # CHỈ GIỮ 20 PHIÊN CUỐI
            # ============================================================

            df_20 = (

                df

                .tail(20)

                .copy()
            )


            so_phien = len(
                df_20
            )


            # =================================================
            # ĐỦ 20 PHIÊN
            # ============================================================

            if so_phien == 20:


                # =================================================
                # TÍNH GIÁ TRỊ GIAO DỊCH ƯỚC TÍNH
                #
                # close của Quote.history:
                # đơn vị = nghìn đồng / cổ phiếu
                #
                # volume:
                # đơn vị = cổ phiếu
                #
                # Ví dụ:
                #
                # close  = 25.5
                # volume = 8,000,000
                #
                # 25.5 × 8,000,000
                # = 204,000,000 nghìn đồng
                #
                # = 204 tỷ đồng
                #
                # Do đó:
                #
                # close × volume / 1,000,000
                #
                # => tỷ đồng
                # =================================================

                df_20[
                    "GTGD_ty"
                ] = (

                    df_20["close"]

                    * df_20["volume"]

                    / 1_000_000
                )


                # =================================================
                # TRUNG BÌNH 20 PHIÊN
                # =================================================

                gtgd_20 = (

                    df_20["GTGD_ty"]

                    .mean()
                )


                status = "OK"


            # =================================================
            # KHÔNG ĐỦ 20 PHIÊN
            # ============================================================

            else:

                gtgd_20 = None

                status = (
                    "THIEU_20_PHIEN"
                )


            # =================================================
            # RETURN
            # ============================================================

            return {

                "STT": stt,

                "symbol": symbol,

                # ---------------------------------------------
                # Đơn vị:
                # Tỷ đồng / phiên
                # ---------------------------------------------

                "GTGD_20": (

                    round(
                        gtgd_20,
                        2
                    )

                    if pd.notna(
                        gtgd_20
                    )

                    else None
                ),

                "So_phien":
                    so_phien,

                "Tu_ngay": (

                    df_20[
                        "time"
                    ].min()

                    if so_phien > 0

                    else None
                ),

                "Den_ngay": (

                    df_20[
                        "time"
                    ].max()

                    if so_phien > 0

                    else None
                ),

                "Trang_thai":
                    status
            }


        # ====================================================
        # 11. RATE LIMIT
        #
        # Vnstock có thể dùng SystemExit khi rate limit.
        # ====================================================

        except SystemExit:

            print()

            print("=" * 70)

            print(
                f"⚠️ RATE LIMIT tại mã {symbol}"
            )

            print(
                f"Chờ {RATE_LIMIT_WAIT} giây..."
            )

            print("=" * 70)


            # ------------------------------------------------
            # Lưu dữ liệu đã làm trước khi chờ
            # ------------------------------------------------

            try:

                save_checkpoint(
                    results
                )

                print(
                    "✓ Đã lưu checkpoint."
                )


            except Exception as save_error:

                print(
                    "Không lưu được checkpoint:"
                )

                print(
                    save_error
                )


            # ------------------------------------------------
            # Chờ reset quota
            # ------------------------------------------------

            time.sleep(
                RATE_LIMIT_WAIT
            )


            print(
                f"Thử lại mã {symbol}..."
            )


            # ------------------------------------------------
            # Retry chính mã hiện tại
            # ------------------------------------------------

            continue


        # ====================================================
        # 12. LỖI THÔNG THƯỜNG
        # ====================================================

        except Exception as e:

            retry += 1


            print(

                f"   ⚠ Lỗi {symbol}: "
                f"{e}"

            )


            if retry < MAX_RETRIES:

                print(

                    f"   Thử lại "
                    f"{retry}/{MAX_RETRIES}"

                )

                time.sleep(5)

                continue


            # ------------------------------------------------
            # Sau MAX_RETRIES vẫn lỗi
            #
            # Lần chạy sau sẽ thử lại mã này
            # ------------------------------------------------

            return {

                "STT": stt,

                "symbol": symbol,

                "GTGD_20": None,

                "So_phien": None,

                "Tu_ngay": None,

                "Den_ngay": None,

                "Trang_thai":

                    f"LOI_CAN_THU_LAI: {str(e)}"

            }


# ============================================================
# 13. BẮT ĐẦU CHẠY TOÀN BỘ MÃ
# ============================================================

processed_this_run = 0


print()

print("=" * 70)

print(
    "BẮT ĐẦU TÍNH GTGD TRUNG BÌNH 20 PHIÊN"
)

print("=" * 70)

print()


for _, row in (
    symbols_df.iterrows()
):


    stt = int(
        row["STT"]
    )


    symbol = str(
        row["symbol"]
    )


    # ========================================================
    # CHECKPOINT ĐÃ CÓ -> BỎ QUA
    # ========================================================

    if symbol in done_symbols:

        continue


    print(

        f"[{stt}/{len(symbols_df)}] "

        f"Đang xử lý {symbol}..."

    )


    # ========================================================
    # CALL VCI
    # ========================================================

    result = get_gtgd_20(

        symbol=symbol,

        stt=stt
    )


    # ========================================================
    # LƯU RESULT
    # ========================================================

    results[symbol] = (
        result
    )


    processed_this_run += 1


    # ========================================================
    # PRINT RESULT
    # ========================================================

    if (
        result["Trang_thai"]
        == "OK"
    ):

        print(

            "   ✓ GTGD 20 = "

            f"{result['GTGD_20']:,.2f} "

            "tỷ đồng/phiên"

        )


    elif (
        result["Trang_thai"]
        == "THIEU_20_PHIEN"
    ):

        print(

            "   ⚠ Chỉ có "

            f"{result['So_phien']} "

            "phiên"

        )


    else:

        print(

            "   ⚠ "

            f"{result['Trang_thai']}"

        )


    # ========================================================
    # CHECKPOINT MỖI 10 MÃ
    # ========================================================

    if (

        processed_this_run

        % CHECKPOINT_EVERY

        == 0

    ):

        try:

            save_checkpoint(
                results
            )


            print(

                f"   💾 Checkpoint: "

                f"{len(results)} mã"

            )


        except PermissionError:

            print()

            print(
                "⚠️ Không ghi được checkpoint."
            )

            print(
                "Hãy đóng file "
                "GTGD_20_VCI_checkpoint.xlsx "
                "nếu đang mở bằng Excel."
            )

            print()


    # ========================================================
    # PROTECT 60 REQUEST/MINUTE
    # ========================================================

    time.sleep(
        REQUEST_DELAY
    )


# ============================================================
# 14. LƯU CHECKPOINT CUỐI
# ============================================================

save_checkpoint(
    results
)


# ============================================================
# 15. CHUYỂN THÀNH DATAFRAME
# ============================================================

df_result = pd.DataFrame(

    list(
        results.values()
    )
)


df_result = (

    df_result

    .sort_values("STT")

    .reset_index(drop=True)
)


# ============================================================
# 16. MERGE VỚI DANH SÁCH MÃ
# ============================================================

result_columns = [

    "symbol",

    "GTGD_20",

    "So_phien",

    "Tu_ngay",

    "Den_ngay",

    "Trang_thai"
]


df_final = symbols_df.merge(

    df_result[
        result_columns
    ],

    on="symbol",

    how="left"
)


# ============================================================
# 17. FORMAT GTGD
# ============================================================
#
# Đơn vị: Tỷ đồng / phiên
# 2 chữ số thập phân
# ============================================================

df_final[
    "GTGD_20"
] = (

    pd.to_numeric(

        df_final[
            "GTGD_20"
        ],

        errors="coerce"
    )

    .round(2)
)


# ============================================================
# 18. SHEET KIỂM TRA
# ============================================================

df_check = (

    df_final[

        df_final["Trang_thai"]
        != "OK"

    ]

    .copy()
)


# ============================================================
# 19. XUẤT EXCEL
# ============================================================

with pd.ExcelWriter(

    FINAL_FILE,

    engine="openpyxl"

) as writer:


    # Sheet chính

    df_final.to_excel(

        writer,

        sheet_name="GTGD_20",

        index=False
    )


    # Sheet kiểm tra

    df_check.to_excel(

        writer,

        sheet_name="Kiem_tra",

        index=False
    )


# ============================================================
# 20. THỐNG KÊ
# ============================================================

total = len(
    df_final
)


ok_count = (

    df_final["Trang_thai"]

    .eq("OK")

    .sum()
)


thieu_count = (

    df_final["Trang_thai"]

    .eq(
        "THIEU_20_PHIEN"
    )

    .sum()
)


no_data_count = (

    df_final["Trang_thai"]

    .eq(
        "KHONG_CO_DU_LIEU"
    )

    .sum()
)


error_count = (

    df_final["Trang_thai"]

    .astype(str)

    .str.startswith(
        "LOI_CAN_THU_LAI"
    )

    .sum()
)


print()

print("=" * 70)

print(
    "HOÀN THÀNH GTGD 20"
)

print("=" * 70)


print(
    f"Tổng số mã:        "
    f"{total}"
)


print(
    f"Đủ 20 phiên:       "
    f"{ok_count}"
)


print(
    f"Thiếu 20 phiên:    "
    f"{thieu_count}"
)


print(
    f"Không có dữ liệu:  "
    f"{no_data_count}"
)


print(
    f"Lỗi cần thử lại:   "
    f"{error_count}"
)


print()

print(
    f"File kết quả: "
    f"{FINAL_FILE}"
)


print(
    f"File checkpoint: "
    f"{CHECKPOINT_FILE}"
)


print("=" * 70)

======================================================================
Ngày kết thúc dữ liệu: 2026-09-16
======================================================================

Đang lấy danh sách mã từ VCI...

Tổng số mã lấy từ VCI: 1753

   STT symbol
0    1    YTC
1    2    YEG
2    3    YBM
3    4    YBC
4    5    XPH
5    6    XMP
6    7    XMD
7    8    XMC
8    9    XLV
9   10    XHC

Chưa có checkpoint GTGD.
Bắt đầu từ mã đầu tiên.

Đã hoàn thành trước đó: 0 mã
Còn phải xử lý: 1753 mã

======================================================================
BẮT ĐẦU TÍNH GTGD TRUNG BÌNH 20 PHIÊN
======================================================================

[1/1753] Đang xử lý YTC...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[2/1753] Đang xử lý YEG...
   ✓ GTGD 20 = 3.31 tỷ đồng/phiên
[3/1753] Đang xử lý YBM...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[4/1753] Đang xử lý YBC...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[5/1753] Đang xử lý XPH...
   ✓ GTGD 20 = 0.03 tỷ đồng/phiên
[6/1753] Đang xử lý XMP...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[7/1753] Đang xử lý XMD...
   ✓ GTGD 20 = 0.03 tỷ đồng/phiên
[8/1753] Đang xử lý XMC...
   ✓ GTGD 20 = 0.27 tỷ đồng/phiên
[9/1753] Đang xử lý XLV...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[10/1753] Đang xử lý XHC...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
   💾 Checkpoint: 10 mã
[11/1753] Đang xử lý XDH...
   ✓ GTGD 20 = 0.05 tỷ đồng/phiên
[12/1753] Đang xử lý XDC...
   ✓ GTGD 20 = 0.04 tỷ đồng/phiên
[13/1753] Đang xử lý X77...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[14/1753] Đang xử lý X26...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[15/1753] Đang xử lý X20...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[16/1753] Đang xử lý WTC...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[17/1753] Đang xử lý WSS...
   ✓ GTGD 20 = 0.12 tỷ đồng/phiên
[18/1753] Đang xử lý WSB...
   ✓ GTGD 20 = 0.03 tỷ đồng/phiên
[19/1753] Đang xử lý WCS...
   ✓ GTGD 20 = 0.10 tỷ đồng/phiên
[20/1753] Đang xử lý VXT...
   ✓ GTGD 20 = 0.08 tỷ đồng/phiên
   💾 Checkpoint: 20 mã
[21/1753] Đang xử lý VXP...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[22/1753] Đang xử lý VXB...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[23/1753] Đang xử lý VWS...
   ✓ GTGD 20 = 0.03 tỷ đồng/phiên
[24/1753] Đang xử lý VW3...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[25/1753] Đang xử lý VVS...
   ✓ GTGD 20 = 9.76 tỷ đồng/phiên
[26/1753] Đang xử lý VVN...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[27/1753] Đang xử lý VUA...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[28/1753] Đang xử lý VTZ...
   ✓ GTGD 20 = 22.98 tỷ đồng/phiên
[29/1753] Đang xử lý VTX...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[30/1753] Đang xử lý VTV...
   ✓ GTGD 20 = 0.60 tỷ đồng/phiên
   💾 Checkpoint: 30 mã
[31/1753] Đang xử lý VTS...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[32/1753] Đang xử lý VTR...
   ✓ GTGD 20 = 0.16 tỷ đồng/phiên
[33/1753] Đang xử lý VTQ...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[34/1753] Đang xử lý VTP...
   ✓ GTGD 20 = 32.11 tỷ đồng/phiên
[35/1753] Đang xử lý VTO...
   ✓ GTGD 20 = 0.97 tỷ đồng/phiên
[36/1753] Đang xử lý VTM...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[37/1753] Đang xử lý VTL...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[38/1753] Đang xử lý VTK...
   ✓ GTGD 20 = 0.15 tỷ đồng/phiên
[39/1753] Đang xử lý VTJ...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[40/1753] Đang xử lý VTI...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
   💾 Checkpoint: 40 mã
[41/1753] Đang xử lý VTH...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[42/1753] Đang xử lý VTG...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[43/1753] Đang xử lý VTE...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[44/1753] Đang xử lý VTD...
   ✓ GTGD 20 = 1.56 tỷ đồng/phiên
[45/1753] Đang xử lý VTC...
   ✓ GTGD 20 = 0.12 tỷ đồng/phiên
[46/1753] Đang xử lý VTB...
   ✓ GTGD 20 = 0.03 tỷ đồng/phiên
[47/1753] Đang xử lý VTA...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[48/1753] Đang xử lý VST...
   ✓ GTGD 20 = 0.05 tỷ đồng/phiên
[49/1753] Đang xử lý VSP...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[50/1753] Đang xử lý VSN...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
   💾 Checkpoint: 50 mã
[51/1753] Đang xử lý VSM...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[52/1753] Đang xử lý VSI...
   ✓ GTGD 20 = 0.04 tỷ đồng/phiên
[53/1753] Đang xử lý VSH...
   ✓ GTGD 20 = 0.25 tỷ đồng/phiên
[54/1753] Đang xử lý VSG...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[55/1753] Đang xử lý VSF...
   ✓ GTGD 20 = 0.90 tỷ đồng/phiên
[56/1753] Đang xử lý VSE...
   ✓ GTGD 20 = 0.03 tỷ đồng/phiên
[57/1753] Đang xử lý VSC...
   ✓ GTGD 20 = 142.97 tỷ đồng/phiên
[58/1753] Đang xử lý VSA...
   ✓ GTGD 20 = 0.04 tỷ đồng/phiên
[59/1753] Đang xử lý VRG...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[60/1753] Đang xử lý VRE...
   ✓ GTGD 20 = 133.10 tỷ đồng/phiên
   💾 Checkpoint: 60 mã
[61/1753] Đang xử lý VRC...
   ✓ GTGD 20 = 0.36 tỷ đồng/phiên
[62/1753] Đang xử lý VQC...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[63/1753] Đang xử lý VPX...
   ✓ GTGD 20 = 19.90 tỷ đồng/phiên
[64/1753] Đang xử lý VPW...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[65/1753] Đang xử lý VPS...
   ✓ GTGD 20 = 0.06 tỷ đồng/phiên
[66/1753] Đang xử lý VPR...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[67/1753] Đang xử lý VPL...
   ✓ GTGD 20 = 68.34 tỷ đồng/phiên
[68/1753] Đang xử lý VPI...
   ✓ GTGD 20 = 136.94 tỷ đồng/phiên
[69/1753] Đang xử lý VPH...
   ✓ GTGD 20 = 0.07 tỷ đồng/phiên
[70/1753] Đang xử lý VPG...
   ✓ GTGD 20 = 0.33 tỷ đồng/phiên
   💾 Checkpoint: 70 mã
[71/1753] Đang xử lý VPD...
   ✓ GTGD 20 = 0.10 tỷ đồng/phiên
[72/1753] Đang xử lý VPC...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[73/1753] Đang xử lý VPB...
   ✓ GTGD 20 = 482.47 tỷ đồng/phiên
[74/1753] Đang xử lý VPA...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[75/1753] Đang xử lý VOS...
   ✓ GTGD 20 = 5.94 tỷ đồng/phiên
[76/1753] Đang xử lý VOC...
   ✓ GTGD 20 = 0.29 tỷ đồng/phiên
[77/1753] Đang xử lý VNZ...
   ✓ GTGD 20 = 1.90 tỷ đồng/phiên
[78/1753] Đang xử lý VNY...
   ✓ GTGD 20 = 0.19 tỷ đồng/phiên
[79/1753] Đang xử lý VNX...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[80/1753] Đang xử lý VNT...
   ✓ GTGD 20 = 0.17 tỷ đồng/phiên
   💾 Checkpoint: 80 mã
[81/1753] Đang xử lý VNS...
   ✓ GTGD 20 = 0.07 tỷ đồng/phiên
[82/1753] Đang xử lý VNR...
   ✓ GTGD 20 = 0.32 tỷ đồng/phiên
[83/1753] Đang xử lý VNP...
   ✓ GTGD 20 = 0.76 tỷ đồng/phiên
[84/1753] Đang xử lý VNM...
   ✓ GTGD 20 = 183.35 tỷ đồng/phiên
[85/1753] Đang xử lý VNL...
   ✓ GTGD 20 = 0.35 tỷ đồng/phiên
[86/1753] Đang xử lý VNI...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[87/1753] Đang xử lý VNH...
   ✓ GTGD 20 = 0.10 tỷ đồng/phiên
[88/1753] Đang xử lý VNG...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[89/1753] Đang xử lý VNF...
   ✓ GTGD 20 = 0.05 tỷ đồng/phiên
[90/1753] Đang xử lý VNE...
   ✓ GTGD 20 = 0.61 tỷ đồng/phiên
   💾 Checkpoint: 90 mã
[91/1753] Đang xử lý VND...
   ✓ GTGD 20 = 155.27 tỷ đồng/phiên
[92/1753] Đang xử lý VNC...
   ✓ GTGD 20 = 0.07 tỷ đồng/phiên
[93/1753] Đang xử lý VNB...
   ✓ GTGD 20 = 1.36 tỷ đồng/phiên
[94/1753] Đang xử lý VNA...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[95/1753] Đang xử lý VMT...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[96/1753] Đang xử lý VMS...
   ✓ GTGD 20 = 0.61 tỷ đồng/phiên
[97/1753] Đang xử lý VMK...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[98/1753] Đang xử lý VMI...
   ✓ GTGD 20 = 0.07 tỷ đồng/phiên
[99/1753] Đang xử lý VMG...
   ✓ GTGD 20 = 0.03 tỷ đồng/phiên
[100/1753] Đang xử lý VMD...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
   💾 Checkpoint: 100 mã
[101/1753] Đang xử lý VMC...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[102/1753] Đang xử lý VMA...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[103/1753] Đang xử lý VLW...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[104/1753] Đang xử lý VLS...
   ✓ GTGD 20 = 0.09 tỷ đồng/phiên
[105/1753] Đang xử lý VLP...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[106/1753] Đang xử lý VLG...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[107/1753] Đang xử lý VLF...
   ✓ GTGD 20 = 0.07 tỷ đồng/phiên
[108/1753] Đang xử lý VLC...
   ✓ GTGD 20 = 0.31 tỷ đồng/phiên
[109/1753] Đang xử lý VLB...
   ✓ GTGD 20 = 0.96 tỷ đồng/phiên
[110/1753] Đang xử lý VLA...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
   💾 Checkpoint: 110 mã
[111/1753] Đang xử lý VKP...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[112/1753] Đang xử lý VKD...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[113/1753] Đang xử lý VKC...
   ✓ GTGD 20 = 0.50 tỷ đồng/phiên
[114/1753] Đang xử lý VJC...
   ✓ GTGD 20 = 148.12 tỷ đồng/phiên
[115/1753] Đang xử lý VIX...
   ✓ GTGD 20 = 547.10 tỷ đồng/phiên
[116/1753] Đang xử lý VIW...
   ✓ GTGD 20 = 2.33 tỷ đồng/phiên
[117/1753] Đang xử lý VIT...
   ✓ GTGD 20 = 0.46 tỷ đồng/phiên
[118/1753] Đang xử lý VIS...
   ⚠ Lỗi VIS: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 1/3
   ⚠ Lỗi VIS: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 2/3
   ⚠ Lỗi VIS: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   ⚠ LOI_CAN_THU_LAI: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
[119/1753] Đang xử lý VIR...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[120/1753] Đang xử lý VIP...
   ✓ GTGD 20 = 0.40 tỷ đồng/phiên
   💾 Checkpoint: 120 mã
[121/1753] Đang xử lý VIN...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[122/1753] Đang xử lý VIM...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[123/1753] Đang xử lý VIH...
   ✓ GTGD 20 = 0.03 tỷ đồng/phiên
[124/1753] Đang xử lý VIG...
   ✓ GTGD 20 = 0.15 tỷ đồng/phiên
[125/1753] Đang xử lý VIF...
   ✓ GTGD 20 = 0.14 tỷ đồng/phiên
[126/1753] Đang xử lý VIE...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[127/1753] Đang xử lý VID...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[128/1753] Đang xử lý VIC...
   ✓ GTGD 20 = 1,373.65 tỷ đồng/phiên
[129/1753] Đang xử lý VIB...
   ✓ GTGD 20 = 62.89 tỷ đồng/phiên
[130/1753] Đang xử lý VHM...
   ✓ GTGD 20 = 550.90 tỷ đồng/phiên
   💾 Checkpoint: 130 mã
[131/1753] Đang xử lý VHL...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[132/1753] Đang xử lý VHI...
   ⚠ Lỗi VHI: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 1/3
   ⚠ Lỗi VHI: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 2/3
   ⚠ Lỗi VHI: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   ⚠ LOI_CAN_THU_LAI: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
[133/1753] Đang xử lý VHH...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[134/1753] Đang xử lý VHG...
   ✓ GTGD 20 = 0.13 tỷ đồng/phiên
[135/1753] Đang xử lý VHF...
   ✓ GTGD 20 = 0.03 tỷ đồng/phiên
[136/1753] Đang xử lý VHE...
   ✓ GTGD 20 = 0.26 tỷ đồng/phiên
[137/1753] Đang xử lý VHD...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[138/1753] Đang xử lý VHC...
   ✓ GTGD 20 = 14.80 tỷ đồng/phiên
[139/1753] Đang xử lý VGV...
   ✓ GTGD 20 = 0.19 tỷ đồng/phiên
[140/1753] Đang xử lý VGT...
   ✓ GTGD 20 = 3.23 tỷ đồng/phiên
   💾 Checkpoint: 140 mã
[141/1753] Đang xử lý VGS...
   ✓ GTGD 20 = 1.67 tỷ đồng/phiên
[142/1753] Đang xử lý VGR...
   ✓ GTGD 20 = 0.65 tỷ đồng/phiên
[143/1753] Đang xử lý VGP...
   ✓ GTGD 20 = 0.74 tỷ đồng/phiên
[144/1753] Đang xử lý VGL...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[145/1753] Đang xử lý VGI...
   ✓ GTGD 20 = 23.64 tỷ đồng/phiên
[146/1753] Đang xử lý VGG...
   ✓ GTGD 20 = 0.04 tỷ đồng/phiên
[147/1753] Đang xử lý VGC...
   ✓ GTGD 20 = 12.45 tỷ đồng/phiên
[148/1753] Đang xử lý VFS...
   ✓ GTGD 20 = 7.57 tỷ đồng/phiên
[149/1753] Đang xử lý VFR...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[150/1753] Đang xử lý VFG...
   ✓ GTGD 20 = 0.08 tỷ đồng/phiên
   💾 Checkpoint: 150 mã
[151/1753] Đang xử lý VFC...
   ✓ GTGD 20 = 0.05 tỷ đồng/phiên
[152/1753] Đang xử lý VET...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[153/1753] Đang xử lý VES...
   ✓ GTGD 20 = 0.04 tỷ đồng/phiên
[154/1753] Đang xử lý VEF...
   ✓ GTGD 20 = 0.32 tỷ đồng/phiên
[155/1753] Đang xử lý VEC...
   ✓ GTGD 20 = 0.19 tỷ đồng/phiên
[156/1753] Đang xử lý VEA...
   ✓ GTGD 20 = 7.76 tỷ đồng/phiên
[157/1753] Đang xử lý VE9...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[158/1753] Đang xử lý VE8...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[159/1753] Đang xử lý VE4...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[160/1753] Đang xử lý VE3...
   ✓ GTGD 20 = 0.06 tỷ đồng/phiên
   💾 Checkpoint: 160 mã
[161/1753] Đang xử lý VE2...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[162/1753] Đang xử lý VE1...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[163/1753] Đang xử lý VDT...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[164/1753] Đang xử lý VDS...
   ✓ GTGD 20 = 7.84 tỷ đồng/phiên
[165/1753] Đang xử lý VDP...
   ✓ GTGD 20 = 0.13 tỷ đồng/phiên
[166/1753] Đang xử lý VDN...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[167/1753] Đang xử lý VDM...
   ⚠ Lỗi VDM: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 1/3
   ⚠ Lỗi VDM: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 2/3
   ⚠ Lỗi VDM: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   ⚠ LOI_CAN_THU_LAI: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
[168/1753] Đang xử lý VDL...
   ✓ GTGD 20 = 0.12 tỷ đồng/phiên
[169/1753] Đang xử lý VDG...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[170/1753] Đang xử lý VDB...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
   💾 Checkpoint: 170 mã
[171/1753] Đang xử lý VCX...
   ✓ GTGD 20 = 0.06 tỷ đồng/phiên
[172/1753] Đang xử lý VCW...
   ✓ GTGD 20 = 0.31 tỷ đồng/phiên
[173/1753] Đang xử lý VCT...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[174/1753] Đang xử lý VCS...
   ✓ GTGD 20 = 1.38 tỷ đồng/phiên
[175/1753] Đang xử lý VCR...
   ✓ GTGD 20 = 0.08 tỷ đồng/phiên
[176/1753] Đang xử lý VCP...
   ✓ GTGD 20 = 0.26 tỷ đồng/phiên
[177/1753] Đang xử lý VCM...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[178/1753] Đang xử lý VCK...
   ✓ GTGD 20 = 60.51 tỷ đồng/phiên
[179/1753] Đang xử lý VCI...
   ✓ GTGD 20 = 202.71 tỷ đồng/phiên
[180/1753] Đang xử lý VCG...
   ✓ GTGD 20 = 32.92 tỷ đồng/phiên
   💾 Checkpoint: 180 mã
[181/1753] Đang xử lý VCF...
   ✓ GTGD 20 = 0.07 tỷ đồng/phiên
[182/1753] Đang xử lý VCE...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[183/1753] Đang xử lý VCC...
   ✓ GTGD 20 = 0.14 tỷ đồng/phiên
[184/1753] Đang xử lý VCB...
   ✓ GTGD 20 = 275.33 tỷ đồng/phiên
[185/1753] Đang xử lý VCA...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[186/1753] Đang xử lý VC9...
   ✓ GTGD 20 = 0.07 tỷ đồng/phiên
[187/1753] Đang xử lý VC7...
   ✓ GTGD 20 = 0.40 tỷ đồng/phiên
[188/1753] Đang xử lý VC6...
   ✓ GTGD 20 = 0.03 tỷ đồng/phiên
[189/1753] Đang xử lý VC5...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[190/1753] Đang xử lý VC3...
   ✓ GTGD 20 = 28.17 tỷ đồng/phiên
   💾 Checkpoint: 190 mã
[191/1753] Đang xử lý VC2...
   ✓ GTGD 20 = 0.19 tỷ đồng/phiên
[192/1753] Đang xử lý VC1...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[193/1753] Đang xử lý VBT...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[194/1753] Đang xử lý VBH...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[195/1753] Đang xử lý VBG...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[196/1753] Đang xử lý VBC...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[197/1753] Đang xử lý VBB...
   ✓ GTGD 20 = 0.45 tỷ đồng/phiên
[198/1753] Đang xử lý VAV...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[199/1753] Đang xử lý VAT...
   ✓ GTGD 20 = 0.06 tỷ đồng/phiên
[200/1753] Đang xử lý VAF...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
   💾 Checkpoint: 200 mã
[201/1753] Đang xử lý VAB...
   ✓ GTGD 20 = 4.14 tỷ đồng/phiên
[202/1753] Đang xử lý V68...
   ⚠ Chỉ có 19 phiên
[203/1753] Đang xử lý V21...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[204/1753] Đang xử lý V15...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[205/1753] Đang xử lý V12...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[206/1753] Đang xử lý V11...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[207/1753] Đang xử lý UXC...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[208/1753] Đang xử lý UTT...
   ⚠ Lỗi UTT: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 1/3
   ⚠ Lỗi UTT: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 2/3
   ⚠ Lỗi UTT: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   ⚠ LOI_CAN_THU_LAI: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
[209/1753] Đang xử lý USD...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[210/1753] Đang xử lý USC...
   ✓ GTGD 20 = 0.03 tỷ đồng/phiên
   💾 Checkpoint: 210 mã
[211/1753] Đang xử lý UPS...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[212/1753] Đang xử lý UPH...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[213/1753] Đang xử lý UPC...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[214/1753] Đang xử lý UNI...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[215/1753] Đang xử lý UMC...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[216/1753] Đang xử lý ULG...
   ✓ GTGD 20 = 0.06 tỷ đồng/phiên
[217/1753] Đang xử lý UIC...
   ✓ GTGD 20 = 0.10 tỷ đồng/phiên
[218/1753] Đang xử lý UEM...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[219/1753] Đang xử lý UDL...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[220/1753] Đang xử lý UDJ...
   ✓ GTGD 20 = 0.08 tỷ đồng/phiên
   💾 Checkpoint: 220 mã
[221/1753] Đang xử lý UDC...
   ✓ GTGD 20 = 0.05 tỷ đồng/phiên
[222/1753] Đang xử lý UCT...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[223/1753] Đang xử lý TYA...
   ✓ GTGD 20 = 0.08 tỷ đồng/phiên
[224/1753] Đang xử lý TXM...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[225/1753] Đang xử lý TW3...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[226/1753] Đang xử lý TVW...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[227/1753] Đang xử lý TVT...
   ✓ GTGD 20 = 0.03 tỷ đồng/phiên
[228/1753] Đang xử lý TVS...
   ✓ GTGD 20 = 2.08 tỷ đồng/phiên
[229/1753] Đang xử lý TVP...
   ✓ GTGD 20 = 0.14 tỷ đồng/phiên
[230/1753] Đang xử lý TVN...
   ✓ GTGD 20 = 4.42 tỷ đồng/phiên
   💾 Checkpoint: 230 mã
[231/1753] Đang xử lý TVM...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[232/1753] Đang xử lý TVH...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[233/1753] Đang xử lý TVG...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[234/1753] Đang xử lý TVD...
   ✓ GTGD 20 = 0.20 tỷ đồng/phiên
[235/1753] Đang xử lý TVC...
   ✓ GTGD 20 = 0.05 tỷ đồng/phiên
[236/1753] Đang xử lý TVB...
   ✓ GTGD 20 = 0.05 tỷ đồng/phiên
[237/1753] Đang xử lý TVA...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[238/1753] Đang xử lý TV6...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[239/1753] Đang xử lý TV4...
   ✓ GTGD 20 = 0.16 tỷ đồng/phiên
[240/1753] Đang xử lý TV3...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
   💾 Checkpoint: 240 mã
[241/1753] Đang xử lý TV2...
   ✓ GTGD 20 = 2.35 tỷ đồng/phiên
[242/1753] Đang xử lý TV1...
   ✓ GTGD 20 = 0.39 tỷ đồng/phiên
[243/1753] Đang xử lý TUG...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[244/1753] Đang xử lý TTZ...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[245/1753] Đang xử lý TTT...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[246/1753] Đang xử lý TTS...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[247/1753] Đang xử lý TTP...
   ✓ GTGD 20 = 0.12 tỷ đồng/phiên
[248/1753] Đang xử lý TTN...
   ✓ GTGD 20 = 0.11 tỷ đồng/phiên
[249/1753] Đang xử lý TTL...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[250/1753] Đang xử lý TTH...
   ✓ GTGD 20 = 0.62 tỷ đồng/phiên
   💾 Checkpoint: 250 mã
[251/1753] Đang xử lý TTG...
   ✓ GTGD 20 = 0.70 tỷ đồng/phiên
[252/1753] Đang xử lý TTF...
   ✓ GTGD 20 = 1.16 tỷ đồng/phiên
[253/1753] Đang xử lý TTE...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[254/1753] Đang xử lý TTD...
   ✓ GTGD 20 = 0.02 tỷ đồng/phiên
[255/1753] Đang xử lý TTC...
   ✓ GTGD 20 = 0.03 tỷ đồng/phiên
[256/1753] Đang xử lý TTB...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[257/1753] Đang xử lý TTA...
   ✓ GTGD 20 = 2.36 tỷ đồng/phiên
[258/1753] Đang xử lý TT6...
   ✓ GTGD 20 = 0.04 tỷ đồng/phiên
[259/1753] Đang xử lý TST...
   ✓ GTGD 20 = 0.20 tỷ đồng/phiên
[260/1753] Đang xử lý TSJ...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
   💾 Checkpoint: 260 mã
[261/1753] Đang xử lý TSG...
   ✓ GTGD 20 = 0.00 tỷ đồng/phiên
[262/1753] Đang xử lý TSD...
   ✓ GTGD 20 = 0.01 tỷ đồng/phiên
[263/1753] Đang xử lý TSC...
   ✓ GTGD 20 = 0.21 tỷ đồng/phiên
[264/1753] Đang xử lý TSB...
   ✓ GTGD 20 = 0.25 tỷ đồng/phiên
[265/1753] Đang xử lý TSA...
   ✓ GTGD 20 = 0.93 tỷ đồng/phiên
[266/1753] Đang xử lý TS5...
   ⚠ Lỗi TS5: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 1/3
   ⚠ Lỗi TS5: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.
   Thử lại 2/3
   ⚠ Lỗi TS5: Không tìm thấy dữ liệu. Vui lòng kiểm tra lại mã chứng khoán hoặc thời gian truy xuất.

In [2]:
# ============================================================
# VNSTOCK_CSDL
# GTGD TRUNG BÌNH 60 PHIÊN GẦN NHẤT 
#
# SOURCE: VCI
# PACKAGE: vnstock Community
#
# OUTPUT:
# GTGD_60 = tỷ đồng / phiên
#
# Công thức:
# GTGD ngày ≈ Close × Volume
#
# Tối ưu:
# - 1 request / mã
# - length = "60b"
# - Mục tiêu ~50 request/phút
# - Checkpoint CSV thay vì Excel
# - Checkpoint mỗi 50 mã
# - Giảm print
# ============================================================


# ============================================================
# 0. IMPORT
# ============================================================

import os
import time
import pandas as pd

from pathlib import Path
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

from vnstock import Listing, Quote


# ============================================================
# 1. CẤU HÌNH
# ============================================================

CHECKPOINT_FILE = "GTGD_60_VCI_checkpoint.csv"
# True: lay lai toan bo du lieu, ke ca khi checkpoint cung ngay da co.
FORCE_REFRESH = False

FINAL_FILE = "GTGD_60_VCI.xlsx"


# ------------------------------------------------------------
# API COMMUNITY = 60 requests/phút
#
# Ta chỉ chạy mục tiêu 50 request/phút
# để có buffer an toàn.
# ------------------------------------------------------------

TARGET_REQUESTS_PER_MINUTE = 50


# Khoảng cách tối thiểu giữa thời điểm bắt đầu 2 request
REQUEST_INTERVAL = (
    60 / TARGET_REQUESTS_PER_MINUTE
)
# = 1.2 giây


# Nếu vẫn gặp Rate Limit
RATE_LIMIT_WAIT = 65


# Lưu checkpoint mỗi 50 mã
CHECKPOINT_EVERY = 50


# Thử lại lỗi thông thường tối đa 3 lần
MAX_RETRIES = 3


# Chỉ in tiến độ mỗi 25 mã
PRINT_EVERY = 25


# ============================================================
# 2. NGÀY KẾT THÚC
# ============================================================

now = datetime.now(
    ZoneInfo("Asia/Ho_Chi_Minh")
)

market_cutoff = now.replace(
    hour=15,
    minute=15,
    second=0,
    microsecond=0
)


# Không lấy phiên hôm nay nếu chưa kết thúc
if now < market_cutoff:

    end_date = (
        now.date()
        - timedelta(days=1)
    ).isoformat()

else:

    end_date = (
        now.date()
    ).isoformat()

# Checkpoint chi duoc dung lai cho cung ngay ket thuc du lieu.
checkpoint_path = Path(CHECKPOINT_FILE)
CHECKPOINT_FILE = str(checkpoint_path.with_name(
    f"{checkpoint_path.stem}_{end_date}{checkpoint_path.suffix}"
))


print("=" * 70)
print("GTGD 60 - VCI FAST VERSION")
print("=" * 70)

print(
    f"Ngày kết thúc dữ liệu: {end_date}"
)

print(
    f"Tốc độ mục tiêu: "
    f"{TARGET_REQUESTS_PER_MINUTE} request/phút"
)

print(
    f"Khoảng cách tối thiểu: "
    f"{REQUEST_INTERVAL:.2f} giây/request"
)


# ============================================================
# 3. LẤY DANH SÁCH MÃ TỪ VCI
# ============================================================

print()
print("Đang lấy danh sách mã từ VCI...")


listing = Listing(
    source="VCI"
)


symbols_df = (
    listing.all_symbols()
)


# ============================================================
# 4. KIỂM TRA
# ============================================================

if (
    symbols_df is None
    or
    symbols_df.empty
):

    raise ValueError(
        "VCI không trả danh sách mã."
    )


if "symbol" not in symbols_df.columns:

    raise ValueError(
        "Không tìm thấy cột symbol."
    )


# ============================================================
# 5. CLEAN SYMBOL
# ============================================================

symbols_df = (
    symbols_df
    .dropna(subset=["symbol"])
    .copy()
)


symbols_df["symbol"] = (
    symbols_df["symbol"]
    .astype(str)
    .str.strip()
    .str.upper()
)


symbols_df = symbols_df[
    symbols_df["symbol"] != ""
]


symbols_df = (
    symbols_df
    .drop_duplicates(
        subset=["symbol"],
        keep="first"
    )
    .reset_index(drop=True)
)


# ============================================================
# 6. THÊM STT
# ============================================================

symbols_df.insert(
    0,
    "STT",
    range(
        1,
        len(symbols_df) + 1
    )
)


TOTAL_SYMBOLS = len(
    symbols_df
)


print(
    f"Tổng số mã: {TOTAL_SYMBOLS}"
)


# ============================================================
# 7. ĐỌC CHECKPOINT
# ============================================================

results = {}


if not FORCE_REFRESH and Path(
    CHECKPOINT_FILE
).exists():

    try:

        checkpoint_df = (
            pd.read_csv(
                CHECKPOINT_FILE
            )
        )


        for _, row in (
            checkpoint_df.iterrows()
        ):

            symbol = str(
                row["symbol"]
            ).strip().upper()


            results[symbol] = (
                row.to_dict()
            )


        print(
            f"Checkpoint hiện có: "
            f"{len(results)} mã"
        )


    except Exception as e:

        print(
            f"Lỗi đọc checkpoint: {e}"
        )

        results = {}


else:

    print(
        "Chưa có checkpoint GTGD 60."
    )


# ============================================================
# 8. XÁC ĐỊNH MÃ ĐÃ HOÀN THÀNH
# ============================================================

DONE_STATUS = {
    "OK",
    "THIEU_60_PHIEN",
    "KHONG_CO_DU_LIEU"
}


done_symbols = set()


for symbol, row in results.items():

    if (
        row.get("Trang_thai")
        in DONE_STATUS
    ):

        done_symbols.add(
            symbol
        )


remaining = (
    TOTAL_SYMBOLS
    - len(done_symbols)
)


print(
    f"Đã hoàn thành: "
    f"{len(done_symbols)}"
)

print(
    f"Còn lại: "
    f"{remaining}"
)


# ============================================================
# 9. SAVE CHECKPOINT
#
# Dùng CSV thay vì Excel:
# - nhanh hơn
# - nhẹ hơn
# - checkpoint chỉ dùng nội bộ
# ============================================================

def save_checkpoint(
    results_dict
):

    if not results_dict:
        return


    checkpoint = pd.DataFrame(
        list(
            results_dict.values()
        )
    )


    if "STT" in checkpoint.columns:

        checkpoint = (
            checkpoint
            .sort_values("STT")
            .reset_index(drop=True)
        )


    temp_file = (
        str(Path(CHECKPOINT_FILE).with_suffix(".tmp.csv"))
    )


    checkpoint.to_csv(
        temp_file,
        index=False,
        encoding="utf-8-sig"
    )


    os.replace(
        temp_file,
        CHECKPOINT_FILE
    )


# ============================================================
# 10. RATE CONTROLLER
#
# Khác code GTGD 20:
#
# Không sleep cố định 2.5 giây SAU request.
#
# Ta chỉ đảm bảo thời điểm bắt đầu 2 request
# cách nhau ít nhất 1.2 giây.
#
# Nếu bản thân API đã mất 1 giây,
# chỉ cần chờ thêm khoảng 0.2 giây.
# ============================================================

last_request_time = 0.0


def wait_for_request_slot():

    global last_request_time


    current_time = (
        time.monotonic()
    )


    elapsed = (
        current_time
        - last_request_time
    )


    wait_time = (
        REQUEST_INTERVAL
        - elapsed
    )


    if wait_time > 0:

        time.sleep(
            wait_time
        )


    # Ghi lại thời điểm request mới
    last_request_time = (
        time.monotonic()
    )


# ============================================================
# 11. HÀM LẤY GTGD 60
# ============================================================

def get_gtgd_60(
    symbol,
    stt
):

    retry = 0


    while True:

        try:

            # ------------------------------------------------
            # Quote VCI
            # ------------------------------------------------

            quote = Quote(
                symbol=symbol,
                source="VCI"
            )


            # ------------------------------------------------
            # Rate controller
            # ------------------------------------------------

            wait_for_request_slot()


            # ------------------------------------------------
            # CHỈ 1 REQUEST / MÃ
            #
            # 60b = 60 bars giao dịch gần nhất
            # ------------------------------------------------

            df = quote.history(
                end=end_date,
                length="60b",
                interval="1D"
            )


            # =================================================
            # KHÔNG CÓ DỮ LIỆU
            # =================================================

            if (
                df is None
                or
                df.empty
            ):

                return {
                    "STT": stt,
                    "symbol": symbol,

                    "GTGD_60": None,

                    "So_phien": 0,

                    "Tu_ngay": None,
                    "Den_ngay": None,

                    "Trang_thai":
                        "KHONG_CO_DU_LIEU"
                }


            # =================================================
            # CLEAN DATA
            # =================================================

            df = df.copy()


            required_columns = [
                "time",
                "close",
                "volume"
            ]


            for col in required_columns:

                if col not in df.columns:

                    raise ValueError(
                        f"Thiếu cột {col}"
                    )


            df["time"] = (
                pd.to_datetime(
                    df["time"],
                    errors="coerce"
                )
            )


            df["close"] = (
                pd.to_numeric(
                    df["close"],
                    errors="coerce"
                )
            )


            df["volume"] = (
                pd.to_numeric(
                    df["volume"],
                    errors="coerce"
                )
            )


            # =================================================
            # LOẠI DỮ LIỆU LỖI
            # =================================================

            df = df.dropna(
                subset=[
                    "time",
                    "close",
                    "volume"
                ]
            )


            # =================================================
            # SORT
            # =================================================

            df = (
                df
                .sort_values("time")
                .drop_duplicates(
                    subset=["time"],
                    keep="last"
                )
            )


            # =================================================
            # CHỈ GIỮ 60 PHIÊN CUỐI
            # =================================================

            df_60 = (
                df
                .tail(60)
                .copy()
            )


            so_phien = len(
                df_60
            )


            # =================================================
            # ĐỦ 60 PHIÊN
            # =================================================

            if so_phien == 60:


                # ---------------------------------------------
                # GTGD ước tính từng ngày
                #
                # close: nghìn đồng/cp
                # volume: cổ phiếu
                #
                # / 1,000,000
                #
                # => tỷ đồng
                # ---------------------------------------------

                df_60["GTGD_ty"] = (

                    df_60["close"]

                    * df_60["volume"]

                    / 1_000_000
                )


                # ---------------------------------------------
                # Trung bình 60 phiên
                # ---------------------------------------------

                gtgd_60 = (
                    df_60[
                        "GTGD_ty"
                    ]
                    .mean()
                )


                status = "OK"


            # =================================================
            # THIẾU 60 PHIÊN
            # =================================================

            else:

                gtgd_60 = None

                status = (
                    "THIEU_60_PHIEN"
                )


            # =================================================
            # RETURN
            # =================================================

            return {
                "STT": stt,

                "symbol": symbol,

                "GTGD_60": (
                    round(
                        gtgd_60,
                        2
                    )
                    if pd.notna(
                        gtgd_60
                    )
                    else None
                ),

                "So_phien":
                    so_phien,

                "Tu_ngay": (
                    df_60[
                        "time"
                    ].min()
                    if so_phien > 0
                    else None
                ),

                "Den_ngay": (
                    df_60[
                        "time"
                    ].max()
                    if so_phien > 0
                    else None
                ),

                "Trang_thai":
                    status
            }


        # ====================================================
        # RATE LIMIT
        # ====================================================

        except SystemExit:

            print()
            print(
                f"⚠ RATE LIMIT tại {symbol}"
            )

            print(
                f"Đã lưu checkpoint. "
                f"Chờ {RATE_LIMIT_WAIT} giây..."
            )


            try:

                save_checkpoint(
                    results
                )

            except Exception as e:

                print(
                    f"Lỗi lưu checkpoint: {e}"
                )


            time.sleep(
                RATE_LIMIT_WAIT
            )


            # Reset timer sau khi nghỉ
            global last_request_time

            last_request_time = 0.0


            print(
                f"Thử lại {symbol}..."
            )


            continue


        # ====================================================
        # LỖI KHÁC
        # ====================================================

        except Exception as e:

            retry += 1


            if retry < MAX_RETRIES:

                print(
                    f"⚠ {symbol}: {e} "
                    f"- retry "
                    f"{retry}/{MAX_RETRIES}"
                )

                time.sleep(3)

                continue


            return {
                "STT": stt,

                "symbol": symbol,

                "GTGD_60": None,

                "So_phien": None,

                "Tu_ngay": None,
                "Den_ngay": None,

                "Trang_thai":
                    f"LOI_CAN_THU_LAI: {str(e)}"
            }


# ============================================================
# 12. CHẠY
# ============================================================

processed_this_run = 0

start_run_time = (
    time.monotonic()
)


print()
print("=" * 70)

print(
    "BẮT ĐẦU GTGD 60"
)

print("=" * 70)


for _, row in (
    symbols_df.iterrows()
):


    stt = int(
        row["STT"]
    )


    symbol = str(
        row["symbol"]
    )


    # --------------------------------------------------------
    # Đã có checkpoint -> bỏ qua
    # --------------------------------------------------------

    if symbol in done_symbols:

        continue


    # --------------------------------------------------------
    # Call VCI
    # --------------------------------------------------------

    result = get_gtgd_60(
        symbol=symbol,
        stt=stt
    )


    results[symbol] = (
        result
    )


    processed_this_run += 1


    # ========================================================
    # CHỈ PRINT MỖI 25 MÃ
    # ========================================================

    if (
        processed_this_run
        % PRINT_EVERY
        == 0
    ):

        elapsed_minutes = (
            time.monotonic()
            - start_run_time
        ) / 60


        speed = (

            processed_this_run
            / elapsed_minutes

            if elapsed_minutes > 0

            else 0
        )


        total_done = len(
            [
                x
                for x in results.values()
                if x.get("Trang_thai")
                in DONE_STATUS
            ]
        )


        print(
            f"[{stt}/{TOTAL_SYMBOLS}] "
            f"Đã xử lý thêm "
            f"{processed_this_run} mã | "
            f"Tốc độ: "
            f"{speed:.1f} mã/phút"
        )


    # ========================================================
    # CHECKPOINT MỖI 50 MÃ
    # ========================================================

    if (
        processed_this_run
        % CHECKPOINT_EVERY
        == 0
    ):

        save_checkpoint(
            results
        )


        print(
            f"💾 Checkpoint: "
            f"{len(results)} mã"
        )


# ============================================================
# 13. CHECKPOINT CUỐI
# ============================================================

save_checkpoint(
    results
)


# ============================================================
# 14. TẠO DATAFRAME RESULT
# ============================================================

df_result = pd.DataFrame(
    list(
        results.values()
    )
)


df_result = (
    df_result
    .sort_values("STT")
    .reset_index(drop=True)
)


# ============================================================
# 15. MERGE
# ============================================================

result_columns = [
    "symbol",
    "GTGD_60",
    "So_phien",
    "Tu_ngay",
    "Den_ngay",
    "Trang_thai"
]


df_final = symbols_df.merge(

    df_result[
        result_columns
    ],

    on="symbol",

    how="left"
)


# ============================================================
# 16. FORMAT GTGD
# ============================================================

df_final["GTGD_60"] = (

    pd.to_numeric(
        df_final["GTGD_60"],
        errors="coerce"
    )

    .round(2)
)


# ============================================================
# 17. KIỂM TRA
# ============================================================

df_check = (

    df_final[
        df_final[
            "Trang_thai"
        ] != "OK"
    ]

    .copy()
)


# ============================================================
# 18. XUẤT EXCEL CUỐI
# ============================================================

with pd.ExcelWriter(
    FINAL_FILE,
    engine="openpyxl"
) as writer:


    df_final.to_excel(
        writer,
        sheet_name="GTGD_60",
        index=False
    )


    df_check.to_excel(
        writer,
        sheet_name="Kiem_tra",
        index=False
    )


# ============================================================
# 19. THỐNG KÊ
# ============================================================

ok_count = (
    df_final[
        "Trang_thai"
    ]
    .eq("OK")
    .sum()
)


thieu_count = (
    df_final[
        "Trang_thai"
    ]
    .eq(
        "THIEU_60_PHIEN"
    )
    .sum()
)


no_data_count = (
    df_final[
        "Trang_thai"
    ]
    .eq(
        "KHONG_CO_DU_LIEU"
    )
    .sum()
)


error_count = (

    df_final[
        "Trang_thai"
    ]

    .astype(str)

    .str.startswith(
        "LOI_CAN_THU_LAI"
    )

    .sum()
)


elapsed_total = (
    time.monotonic()
    - start_run_time
) / 60


print()
print("=" * 70)

print(
    "HOÀN THÀNH GTGD 60"
)

print("=" * 70)

print(
    f"Tổng số mã:        "
    f"{len(df_final)}"
)

print(
    f"Đủ 60 phiên:       "
    f"{ok_count}"
)

print(
    f"Thiếu 60 phiên:    "
    f"{thieu_count}"
)

print(
    f"Không có dữ liệu:  "
    f"{no_data_count}"
)

print(
    f"Lỗi cần thử lại:   "
    f"{error_count}"
)

print(
    f"Thời gian chạy:    "
    f"{elapsed_total:.1f} phút"
)

print()

print(
    f"File kết quả: "
    f"{FINAL_FILE}"
)

print(
    f"Checkpoint: "
    f"{CHECKPOINT_FILE}"
)

print("=" * 70)

======================================================================
GTGD 60 - VCI FAST VERSION
======================================================================
Ngày kết thúc dữ liệu: 2026-09-17
Tốc độ mục tiêu: 50 request/phút
Khoảng cách tối thiểu: 1.20 giây/request

Đang lấy danh sách mã từ VCI...

Tổng số mã: 1753
Chưa có checkpoint GTGD 60.
Đã hoàn thành: 0
Còn lại: 1753

======================================================================
BẮT ĐẦU GTGD 60
======================================================================
[25/1753] Đã xử lý thêm 25 mã | Tốc độ: 48.3 mã/phút

KeyboardInterrupt: